apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  interval: 5m
  timeout: 5m
  releaseName: longhorn
  values:
    persistence:
      defaultClass: false
    longhornUI:
      replicas: 1
    defaultBackupStore:
      backupTarget: s3://tinyrack-homelab@us-east-1/clusters/tinyrack-homelab/longhorn
      backupTargetCredentialSecret: tinyrack-homelab-s3-secret
#    ingress:
#      enabled: true
#      host: longhorn.internal.tinyrack.net
#      tls: true
#      tlsSecret: letsencrypt-wildcard-cert-tinyrack.net
