persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
longhornUI:
  replicas: 1
defaultSettings:
  defaultReplicaCount: 1
  concurrentAutomaticEngineUpgradePerNodeLimit: 1
defaultBackupStore:
  backupTarget: s3://tinyrack-homelab@home/clusters/tinyrack-homelab/longhorn
  backupTargetCredentialSecret: tinyrack-homelab-s3-secret
ingress:
  enabled: true
  host: longhorn.intranet.winetree94.com
  tls: true
  tlsSecret: letsencrypt-cert
