---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-smtp-secret
  namespace: ghost-tinyrack-system
spec:
  encryptedData:
    smtp_password: AgB/nQxo4oaCn39Zk3KGxkOeVTEn5LWS5lZGWrOlkYBKS7fg3jZLSDpFMrdQnLfnuEnGJjg0sYTlqmMYcj6n+rG+46tPLFTNwY9cvRmKgOMUltLMaP4OAXzVzSawpEgUCdXeqAByLWId2ocoyzgJ5OEiAD8WMSZmmHv9tOXg4VB3SQv5LnDAB1atQuYL6bBdugRbiDBuuJXiOGodWuJGBuQyT+HMIoYezFg4uejPtq7nQlMXd+8lcXRFB/F5gKPlbF5ec9QCut/7wazGxfXTJ+1q4mm18PXpB58yPCxpL7ZokrtRZumJc+LBPKlWJ+aVQO2IdcupBlGzmPx6DuRzY9lsAvl2CgL2jFX5V3bwAe0u98/xD8r3hczrwqQX359SFe+TjMJOzFOnUHco6eEhpiQyHA/SO3gjpliyiCsLGBw/XASAhM5adl3Pl8YDHhDmMhJj2vyPlzbqDYTKJlXa00ThOLOEvyCybFqlJC5cRBzKAblHO/FysEbTh8kTh5vxbEcVwN8FBF3GbCmaIeA1HjuTrg6BOTv6mc1NcTaS89rpp8qcYZ3p5zUii8LHpSxRgr5Jql6dqwUrZBexYa+l6rE4zVCixuf1NrW/SA9FPvMZ+vCWl8c9dbEdNReP6WSxP6DUTZqaJWcMNft3utg65bU283KaTlJa91K3t1mjl19Rom2LQE6InaSR/20sqQxxbwxepmU3tlFMmRoINuFiCKR7UTP+3OTpEx+XwR9S/cginihyswW9LvQT
  template:
    metadata:
      name: ghost-smtp-secret
      namespace: ghost-tinyrack-system
