apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: syncthing-database-backup-store
  namespace: syncthing-system
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://tinyrack-homelab/apps/syncthing/database
    endpointURL: https://storage.intranet.winetree94.com
    s3Credentials:
      region:
        name: tinyrack-homelab-s3-secret
        key: AWS_REGION
      accessKeyId:
        name: tinyrack-homelab-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: tinyrack-homelab-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: syncthing-database-cluster
  namespace: syncthing-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie@sha256:c2a773217853c6e0ffe7da9c37ea456466efb20cf844f27511a73fa6a81e3152
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: syncthing-database-backup-store
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-strict-local
      volumeMode: Filesystem
  bootstrap:
    initdb:
      database: syncthing
      owner: syncthing
      secret:
        name: syncthing-database-user-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: syncthing-database
  namespace: syncthing-system
spec:
  name: syncthing
  owner: syncthing
  databaseReclaimPolicy: retain
  cluster:
    name: syncthing-database-cluster
  schemas:
    - name: juicefs
      owner: syncthing
      ensure: present
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: syncthing-backup
  namespace: syncthing-system
spec:
  schedule: "0 0 */4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: syncthing-database-cluster
