---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: syncthing-database-user-secret
  namespace: syncthing-system
spec:
  encryptedData:
    password: AgCPhsWTU09OHFBIwNKkoFV42ZUDA6YUOZBa271k7AyDWw3oou06uCuGpBiC8IZZVUyIQSIVbrJ0DPrLqv50WIg/ioMZLfs39XEw4bnfGv6ZqTLFVTYd2shR4byV0hPmPb4+VipsJ0NPopr0bCv6679ZZoXfvtqC/0JH67JDx9i1hAHiZPTiql2doI8g/lVKy3B/8vOfPl98ESCtSM1zdCpQnlt3RUcJrt5AcSqCiXzlnBesl5sYfPtbmU7sREsG1W6DOfTqa9p2l7J2i/hie4kyzCVeBbI76eDvvG+OgC82FZgUy5HgqkjNWSpjKUXlxzM/bdz2bNI1zEaAk7q+oq+6P/i8kOvd31MsPVZbaHyWuULMtv/kkMq1oGPJHoOLIO+ED2lh4IiGc9eANOOn/rrXwDtpUbnub/vGd7yFrneGQgJWWAcqPNyAaeg545t489Y2GGlWqPc21n4ie2sJV3t1TFtp6j9uTTD7euAgc8+Xnz0AuM8IQsfKFhY3kJBV+pSzjRbqML7TdrwitKrf1aWIH2ubGmR5wLItnUCc2HQ9witfx4iyMKmfXtBQbE5cKtbHW1v2iW57MM2RvGWrsdhoWMgLbC1Y1Eb6IfFqRmz9Y685UnZ/tx8DVXHbwPu+Beg8IRcSExnDh8tH4VcBnW1ezWVQTx/Ku+S4KgrOFKXZvJSxBtEKMbzJeU6Q0F6joiiAVv/Cfk8JEPivNr+7+yxqhpoAV5Ntzg9S0ERfzvujIFa5s8Tru4gVVi1Su6TNVSo=
    username: AgALdvhBUKYhVKrJxWwoyXgX5NwJ9DSlOSmrRtPOXifrBptBe24d15Fe62M+MGJlnJgbRVTydFfSxhKl+WX5hnONo6MyHuLTyVvHIucvwAZ1vrnbtisWf7+RH/p5JlriwC7Xinjh+wS2WnXDaXN0jWDEMS1dvJ/IwycOLkzoFfwlagjc8OhqQ/+7XcvsQX16jMYpHXcragihZtCVk7MRAjh067CT6YIh9reKtT1/amvnxdpanv7yVuLm04isy6lwwo1kLSRCCxiQhtSLEjaC5ZMzh2cZVkVfg5roJpg2gfaew2jJryIzjfMhihU/tuYDMamaeQb0P7tf4AQAKHAGQ3iE0sPtqaquzfZmnH8bOa1t/qmziLI3b1/LV7e0PGshqRmyca98FWVef1KQQtIeXH/5Drw6q716TprlcLeXdic5oM4ibIqik/AdDsoVZRlE9aBv+wF1Dc76MwBysIcOK2L1MGexIy6LSf7lvEFwXNw7KJSptOMsNvoaxnvzHVpQ7GuXkutK5Z1NRdvvBJOUp71Vtye4hoN8h94caZIf/2wmcrOMaSiIP78zah4PBdlhnpvZ1nni8t/u2PXJDaS5FwOCJCyNP6bPLNn6jHLVQVsqUZUItdsh6hlM1JOG3MoIqIL6MSRGcaRAMw/is7u6crNbRzwOiRbv/HbcLO97tZkCrq2cGe8IufmRzrOx5H5FW7MstWx1uqGvu6w=
  template:
    metadata:
      name: syncthing-database-user-secret
      namespace: syncthing-system
