apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - beszel.namespace.yaml
  - beszel.pvc.yaml
  - beszel.deployment.yaml
  - beszel.service.yaml
  - beszel.ingress-route.yaml
  - beszel.network-policy.yaml
