apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: redis-operator
  namespace: kube-prometheus-stack-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - ot-redis-operator-system
  selector:
    matchLabels:
      name: redis-operator
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
