apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nextcloud.namespace.yaml
  - nextcloud.database-user.secret.yaml
  - nextcloud.database.yaml
  - nextcloud.database.cilium-network-policy.yaml
