---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-database-user-secret
  namespace: nextcloud-system
spec:
  encryptedData:
    password: AgAFSvbRsIQFMEwyD33UeOnlpnTFDFsm5ejz7v9x0zuLANDQ/5TSbY6R4VrpsbPUwDCRtA7eKJYeTRsfa6SW11w8FLFWFf3LVQTkU4IAQSeFJcJDW5djxX2kg9l2kB5TvbjYjrxZ7hSg/BCRH0H7CaFEuCExLRbv8PZqwQaMbLGuc4oVgtnYxEMRfLjRuBLjK3S5m2IgK0DHVMKMiiZZ52e61oeYQC33FUG7uGPjsXEnoW5IyicsasnRnQjHzqlfDbUnag5D3jvOoF5WZpos0TQvg+mLeHqzdXeYQRqAunB12Whgscf38QK1pEEV50Rz39xkYR4miZnE0oyppYZmMbBDH7NPDCHCZBr6wueaZhamZL6lWX+Fda4+vDMz/nC5tV6DhPtUs8El4XV5O8rWt92RUpk5Rem2UHaUPtF3qGBqQH6oigj7pDf68tlJk3cCDFoIYol2lJdFOfzdkIP5s3eqhDI8BeCAtXFDm+qkotAkwxTLB6bWrs55JVg5ila0dh/yFw0rIeoNDWkh5ROsMNXE7xOWQ9KsRbp95MzajvGeuRzv2NSSrMFChLlMN9BUZdcLzL2VPq5kIBo5w157ER744IoCsqTQhcbkyXmP13jjSS4VKrIyIX3CNcxM4gUFm3//+tf8wv5bGy7a0riB/5K2cZ7luUmmtsScg97dOA2Of3ZhLaMyyjUlkjGbNDi2R6m8TAAyb1V3CXb0vIhhQGRttELV46LRsGz5N+F6mXlxgw==
    username: AgAVDX5GaR7OTKJxlM/+5TqcIu/UURhvn79MDzrtkNGdkJklpV8Js7Vxz0ueN3X6hd2/e5H2HOqUCbclZX2t7u8edkhHjiQKdweheipMwCzp+WUBNoVKZTXZseALlPk0IndwVBY9keYaweRiLsspgeHX/cQmnRyL1CKbAOTBxKB/gMR/kRbeCp0lzP+YuJgHBliKuSqH8PphlV5mub7bAMP9//f/x8i10M0JaIlisGPWFBO5njZ4GsMoZaE0WJ13I81xFrX1qo9QvEIlhO3o8qVHK7cFVAPq4/YtmB5TX2vCJuyrpKGBa209T6ruo/dIRLvoi+cKORmGawnh2uz5WqXBMlIF00nrTeNPu/2b9GvtTyf0UyL33Td9hLV+ZORizoPhw6EtaTWUATYehM21yjSq8J7ZdJax3JHHh5wRNyc7X+i4Jld+sa+vjxnArhw+K+B2QX74eh0YXalRWtpxQ3xJcC41VcBw4Qx/m2rI1D6mFXAiK2ttYNy56u3ICqy2cdt5lOfkHsfYgo5I9JIXLP7qQHIcYMUkxjNmNd+OCLNPZGmMnakGI0KsrABph/INLsGcsqnldpVDqWggyaGoPaGJDYWM0iemVsAKzs8Pb9nvRopFpPNKellCYNylaGUBbsQ0apEcxFq4xJfpYHe809326eLezKtpbmT6TcOipjGo4fQXINYdqPJUshNCSBVfKIe2YFC46PUFkxg=
  template:
    metadata:
      name: nextcloud-database-user-secret
      namespace: nextcloud-system
