apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-helm-release
  namespace: infisical-system
spec:
  releaseName: infisical
  interval: 5m
  chart:
    spec:
      chart: infisical-standalone
      version: "1.7.2"
      sourceRef:
        kind: HelmRepository
        name: infisical-repository
        namespace: flux-system
  values:
    sdf: true
