apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ot-redis-operator-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    networking.tinyrack.net/isolation: enabled
