apiVersion: recovery.tinyrack.net/v1alpha1
kind: VolumeInventory
volumes:
  - namespace: beszel-system
    pvc: beszel-data
    targetVolume: beszel-data
    storageClass: longhorn-strict-local
  - namespace: bulwark-system
    pvc: bulwark-admin
    targetVolume: bulwark-admin
    storageClass: longhorn
  - namespace: bulwark-system
    pvc: bulwark-admin-state
    targetVolume: bulwark-admin-state
    storageClass: longhorn
  - namespace: bulwark-system
    pvc: bulwark-settings
    targetVolume: bulwark-settings
    storageClass: longhorn
  - namespace: bulwark-system
    pvc: bulwark-telemetry
    targetVolume: bulwark-telemetry
    storageClass: longhorn
  - namespace: karakeep-system
    pvc: karakeep-data-storage
    targetVolume: karakeep-data-storage
    storageClass: longhorn
  - namespace: karakeep-system
    pvc: meilisearch-storage
    targetVolume: meilisearch-storage
    storageClass: longhorn
  - namespace: n8n-system
    pvc: n8n-storage
    targetVolume: n8n-storage
    storageClass: longhorn
  - namespace: rustdesk-system
    pvc: rustdesk-data
    targetVolume: rustdesk-data
    storageClass: longhorn-strict-local
  - namespace: wg-easy-system
    pvc: wg-easy-data
    targetVolume: wg-easy-data
    storageClass: longhorn-strict-local
