apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: litellm-database-backup-store
  namespace: litellm-system
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://tinyrack-homelab/apps/litellm/database-18
    endpointURL: https://storage.winetree94.com
    s3Credentials:
      region:
        name: tinyrack-homelab-s3-secret
        key: AWS_REGION
      accessKeyId:
        name: tinyrack-homelab-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: tinyrack-homelab-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: litellm-database-cluster
  namespace: litellm-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.6-standard-bookworm@sha256:cdb5c283a473507f7c597ea7e045d1a5e8efcbc4c5101aada013af9bd37ccc43
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: litellm-database-backup-store
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-strict-local
      volumeMode: Filesystem
  externalClusters:
    - name: litellm-database-recovery-source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: litellm-database-backup-store
          serverName: litellm-database-cluster

  enableSuperuserAccess: true
  superuserSecret:
    name: litellm-database-superuser-secret

  # 재해 복구 시 recovery overlay에서 initdb를 이 설정으로 교체한다.
  # bootstrap:
  #   recovery:
  #     source: litellm-database-recovery-source

  bootstrap:
    initdb:
      database: litellm
      owner: litellm
      secret:
        name: litellm-database-user-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: litellm-backup
  namespace: litellm-system
spec:
  schedule: "0 0 */4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: litellm-database-cluster
