apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  namespace: litellm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm-container
          image: ghcr.io/berriai/litellm-database:v1.83.7.rc.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: litellm-database-user-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm-database-user-secret
                  key: password
            - name: DATABASE_URL
              value: postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@litellm-database-cluster-rw.litellm-system.svc.cluster.local:5432/litellm
            - name: LITELLM_MODE
              value: PRODUCTION
            - name: LITELLM_LOG
              value: ERROR
            - name: LITELLM_LOCAL_MODEL_COST_MAP
              value: "True"
            - name: STORE_MODEL_IN_DB
              value: "True"
            - name: SEARXNG_API_BASE
              value: "https://search.winetree94.com"
          envFrom:
            - secretRef:
                name: litellm-secret
            - secretRef:
                name: litellm-database-secret
          args:
            - "--config"
            - "/app/proxy_config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /app/proxy_config.yaml
              subPath: config.yaml
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 10
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 10
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config
