---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-database-user-secret
  namespace: immich-system
spec:
  encryptedData:
    password: AgBqLBdM9Trv3SP69A/IxuGTFPnd7b6JFwu+Xd4BOZ+mZyhiiInBIOaQ4bL7/VFgFKYWBvUzRcH2gTAZJuy828LT1hlxGy3aRBZFmxh2rLZZ3PNlR2nyxA0xhXTBjmPwL85KJ9jkalPiU5XGM+vSzltvmHMbcznT3s7ST0gBmtacrqNli1EZu/POdZi7yAiBceY/LiOJFhapbNRq9/NoK/cfUb7ZIvSF2saGqxsnVYA1GXP2MjJJsbhq2ryBAxnNRb4UxHkifYBdwVe6fbXZQOoO3tVPbVEhLctf+kFkNq/LplzrqLU/1zVpLJAoJ6gPSIf9EFPNxc7UYSYpZ6Uu0f6o72fK0hKWlVpX1OR9leOaqmV/354g9e//aGptfp0Df1X3wDwECLVClF4ez4+7Et1UnaseMLVDlDMt3saGUA8jbXypb57ULdddUpXt+NQCyGYIf2dqPIdup0JGjn0Ee6DpPzavSJO5HnJGciOjGCV+7mjWETtQ89JLRJRjreEOGzMyrZxqVOc8VvaEp3bwwYGAZTtrVVppijTRIqNWpsD0UzF7hWNeCUl8EPZg3WYgH3XwZlfjbXM1lWH5GTe1vGD9WSqRscuuVYf8hoz7rBU1r0opNQjisnkapFOY2vf4Nj9TcAEJihK611VhX/nINvmbspQmrR2T/IEQ1ERO1S07cwSvQbERno1D5LnZSwFhEgt9XejNc612GQvPm/VR4pI7v4VG4LF0J78ZGcvpo+XMlZ5Wv2n2iV7szbUrJ4yYR04=
    username: AgAUVqQyLnfwx4lVRmZnHJguFaYG82LcJ28tG8nsj8wcCfOEhJWlW1F1Mr2sb5DXIV4bMycxwP6uKg3DkC/iAWlsvTkKserl6klLGk5EHMx9bVJGpG6JTU947vc77C4Cx6Tu5Xw2UvOzmZs64CPAQCkf6ZjjW1Ale5Ozm0/WcELCXmHJRka2ZqRbynhi2KwkDcVxCoR42/C6as9rNjj0cJOgrhHdnsVwWfL1MxnHxfdlX5RwIQwgFjowOB33w/PudK0QxwoRG0BpPsawUKZvYXslTiFkH6rKOv45RvwPN0AoB+b3JFstqXPsQVYTvt3mNNKD6Eoq4j9jwxBYvQtsaAoJddFmC6bM9kp0TZ8QjWLPWaHvrE+/KVT6xOgOWWEKvHBHhAWRoFx9Z5LJgIFqPjjcQerkZQ62CZki9Hn79oAJ4ySTFaqW4FDUUtpuuBd2x22+E0wDeLKPkL2sbV8WIP+ERa6p0QYkfAaMRojlzgaLJA1ySRcvLeLGbW5uT+9xecVso2qfpIp7bxKr3xkxRl71RQqNawZnbFFIW/gsjvBksaT0ZQ28UXIjdHwOv+OL6TgEwjrJDmGFwC9uk93FVXs75EXrMBChevHwrTyn0nKv2XM4Y1spIghX4AriystqbECg/keggrdvlyCdF6tiZf7GXVBqWnwW2ql0FUAqYU+QDDGdfPsR8NXSFcC+fAx2X3//b8Gsexo=
  template:
    metadata:
      name: immich-database-user-secret
      namespace: immich-system
