apiVersion: v1
kind: Namespace
metadata:
  name: searxng-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: karakeep-system
  labels:
    networking.tinyrack.net/isolation: enabled
