apiVersion: v1
kind: Namespace
metadata:
  name: davinci-resolve-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: wg-easy-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: rustdesk-system
  labels:
    networking.tinyrack.net/isolation: enabled
