apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nextcloud.admin.secret.yaml
  - nextcloud.helm-release.yaml
  - nextcloud.ingress-route.yaml
  - nextcloud.cilium-network-policy.yaml
  - nextcloud.traefik.cilium-network-policy.yaml
configMapGenerator:
  - name: nextcloud-values
    namespace: nextcloud-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
