apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud-system
spec:
  interval: 5m
  timeout: 15m
  releaseName: nextcloud
  targetNamespace: nextcloud-system
  storageNamespace: nextcloud-system
  chartRef:
    kind: OCIRepository
    name: nextcloud-repository
    namespace: flux-system
  install:
    remediation:
      retries: 0
  upgrade:
    remediation:
      retries: 0
  valuesFrom:
    - kind: ConfigMap
      name: nextcloud-values
      valuesKey: values.yaml
