apiVersion: v1
kind: Service
metadata:
  name: traefik-external-cloudflare
  namespace: traefik-external-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: traefik-external
    meta.helm.sh/release-namespace: traefik-external-system
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: traefik-external-traefik-external-system
    app.kubernetes.io/name: traefik
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: cloudflare
