apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - juicefs.mount-priority-class.yaml
  - juicefs.helm-release.yaml
configMapGenerator:
  - name: juicefs-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
