apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - multus.crd.yaml
  - multus.service-account.yaml
  - multus.cluster-role.yaml
  - multus.cluster-role-binding.yaml
  - multus.config-map.yaml
  - multus.daemon-set.yaml
