apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-daemon-config
  namespace: kube-system
data:
  daemon-config.json: |
    {
      "chrootDir": "/hostroot",
      "cniVersion": "1.0.0",
      "logLevel": "verbose",
      "logToStderr": true,
      "binDir": "/var/lib/rancher/k3s/data/cni",
      "cniConfigDir": "/host/var/lib/rancher/k3s/agent/etc/cni/net.d",
      "multusAutoconfigDir": "/host/var/lib/rancher/k3s/agent/etc/cni/net.d",
      "multusConfigFile": "auto",
      "socketDir": "/host/run/multus/"
    }
