---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guacamole-oauth-secret
  namespace: guacamole-system
spec:
  encryptedData:
    client_secret: AgCCg97EkI+R+2tIXCMgpTsO8e3ehAm9EgQL5OBihfERZJXy9JuvORCtrQ3oWvmB7XnsuZfAB6QoEPAXQAMZHTWvGNHkzT2eUSU81byoJ5kzIchfi10Wm2J6LxOGVB3AN374qZFI9kjfdRK94fDv9sx3zofeLx+miGWdE0P0bGgwWLVNC5qwSNIFPofMEHTFYc4T+QFxYSgjCpkGVEfHctHYOC3yFuTsYW1twVJlLbx+u6bFK9TulgiRXwUEL8mqVWc1I2N/ofZJxWn5HO5FO8QPzgbecwqssIHumtYCEG1AzoVGj8yzI/nNlZ8nmfdKc7BTRLaAPuD1TUUxy0g29b5qFqx+xl6rFZRs1Lc0Vt+ZbfksqFiVirHogJ/ckUd5v+b2nPvcF5JEFpcBaMaol8y3LyR54yNLgvmChFQfgzmL4aPaFymyvI2ZsFswVD/0IMPguYwj6yqf1zaNI6AZ4wsjWQy3wRpvhBs1UdHz/yQvJcJRdJfv0N8hxlAoZVD4C57HpsfGmdy8bgTzNQ5+XcNE6ZEAqlqQGhUlPLYCarmbCwWwS/CHW4l+A/2eZ4iMcmcXafKGS1XzLHpYpvYqYDQI7/7mpy80KTL/dWkedHpoFwlHyfsKFuPWW7IebbuV8wL+hR8mx6HZK460IoKEw+qu4iqPzYlr/9hy9qOMqk0hOKJ4U+y/2XVoS8eEGzGBhhgRr3XF8+wLlmEifqFq5FEcSic436a2J0SX7yGs7AGCKWfHkx/KO2Smi0SIfSme5RVN20Aymb5KKWDcqb2xl/ZT
  template:
    metadata:
      name: guacamole-oauth-secret
      namespace: guacamole-system
    type: Opaque
