apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: guacamole-database-backup-store
  namespace: guacamole-system
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://tinyrack-homelab/apps/guacamole/database-18
    endpointURL: https://storage.winetree94.com
    s3Credentials:
      region:
        name: tinyrack-homelab-s3-secret
        key: AWS_REGION
      accessKeyId:
        name: tinyrack-homelab-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: tinyrack-homelab-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: guacamole-database-cluster
  namespace: guacamole-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-bookworm
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: guacamole-database-backup-store
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-strict-local
      volumeMode: Filesystem
  monitoring:
    enablePodMonitor: true
  externalClusters:
    - name: guacamole-database
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: guacamole-database-backup-store
          serverName: guacamole-database

  enableSuperuserAccess: true
  superuserSecret:
    name: guacamole-database-superuser-secret

  # 신규 클러스터 프로비저닝 시 주석 처리
  # bootstrap:
  #   recovery:
  #     source: guacamole-database

  bootstrap:
    initdb:
      database: guacamole
      owner: guacamole
      secret:
        name: guacamole-database-user-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: guacamole-backup
  namespace: guacamole-system
spec:
  schedule: "0 0 */4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: guacamole-database-cluster
