---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghost-smtp-secret
  namespace: ghost-system
spec:
  encryptedData:
    smtp_password: AgBjMrbdPQA9PcKPDkiaBNiwaXsCeDib3oyacCC2S/3KQxppfIzaa6xA4zH2UrvnHl6CGzb9gAQO/CCERPM7hbMR+lXpfUBX1NdIpESivF0zkdtXxAy0TZ1XQCuL5q7iTkBVA5IvqZYzDVD7DEXiEsku6kBF51hlr1HepKtHWv2RWh/0PdkNON2rgpaladvIaN292sJ1rp9Aj2KXJ45SNywvCa67vmq67oLte8/PatPXSEjeQWiVps0Mip5bxpYNIVjWD5PKrdPWZgiIeHXNWJpqxFfxWJIx29FyX65I3vR46gcDWK/dR/Tdx5+ZRbs3p6ZZFSqbdxzqgAcmuhN/0QXB9wn5KaurxrmysgK/IKsz1WTmyYGt/mfusReTLd7LDWL6egtz49vbAcDqem0lgsQEibbJg2J8HaXW9epJ1ud1vbAODM9JXScKmXPhzGnwNwgT3WjxnSp7MaDd129K9v7/wdUxj9XxUsKf6Bsa2BrxrvcSllFBPDnB7NxAN6o661p1C9SUOx6XJwQo3lbuM6P1uG7BTC/1rQ+qOzPKdPftWqaEPqwlhxPt+3iU/N6vhPKCnSQf+i54wcigD8Go6MKz9ltgd3l7O/nKbC3iaLgVtGk3u5N+3CYuBBxo+42L92u1AND2MH1FlMBPH/vmr67mH3zN0F6nOA1t3LO1AdTZKRCmhBUoNz9d3rrvd86Hp2Z4RwTz07KNNJyd7XEzGnlkG+tGWLefypSpvlHbeTBUwTdAEIewN7c5
  template:
    metadata:
      name: ghost-smtp-secret
      namespace: ghost-system
