apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-migration
  namespace: flux-system
spec:
  interval: 15m
  path: ./apps/base/immich/migration
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
