apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vivident-tailscale-router-deployment
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./apps/base/vivident-tailscale-router
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
  dependsOn:
    - name: multus-deployment
