apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-home
  namespace: syncthing-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app: syncthing
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/longhorn-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-strict-local
  volumeMode: Filesystem
