---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cliproxyapi-database-superuser-secret
  namespace: cliproxyapi-system
spec:
  encryptedData:
    password: AgBJTm81IVYcE5+tx+n+6mjCy0RLlpvtB1nS43oz7uwHay3j2+A8WI2nE6EBTviWy6DqwZNjW1srOpJlW2YyFMtOll/iYBroCuzcLXjh9YfaAPChcxKbZA2abQLKFNgPI2mdJ4oSWNWYN9GlQ4jjJrJIdT/K1l04WRTUnrDHERJoPfv7VLWJHIi2fUYcssLyXXSlbYod5/CeXbQCDyOlBxnntaDI0YtV6yjS2aHBXE3AB2WWgKVNBGE7nEV2zgTef8kEkJZVvCGcIwt3zQqFyAXgfugthpPvTv+txhcKBmb2WPglJkB1pVrK01zTjcA97zgxeEW5USOPJEmaGSuQ63zfnbSrg9ejp02bSnRmoQpqnvLX0uV8bg0vqbYjCFfe7w4bZxvPUnFzJuwVgILsI2Tjmd0QFNufYlEN0GV5Fd9kZHkLUY5o1pftxGzWg2lDteok4lb4W02C+Ni60DDdZCKc0sZt2geFmiWXNPxvNr2RWGAnSloDydPIGrMLRar34o6xLmhY+OgNJdEB8dJ49qbvOfzBcJGmaCh8CHqYgmjjORkdJpdh1coWaIUkNi3Y7MJZwdJiwG7dBcjaGdC6Thkk7iMYLobOXvDHwN6lLXCKTXq+06r6+UGhcMsWX3ak5W5znMxNwPNtbykz9Shz7D+nrGRYJR+xyhwoYxnn02CpHRMg7c4hoioLrf/QbzQ4sV0rsQWMsPdoSp/WotJMQtj1aJyiZ/RIOMVq+ErTMP7Rww==
    username: AgBcu07s+kBemQp/8XewWDNrOZn4qZdaExnITQUU66OlYYsVvfUwxUxY1mpmy/djiBNdV6+h3OW40n/IV44gElUqrJ1A0KIZuzXipHWVtVy+pMnxRgig+wohtZbwPaD49b9tpwjUf65RVaU9F4sGe2Esucbtw1VyoPQ+mYKdmcEe69yv9HxajA2nSZMVyKNunbD53mYkKRqdmi0Da6i3TP34TvTcArqE6e7omFAu/95H2TrhpqjlcuXEwyhRDntyfNoX7ias5GPLJ8PKHC8vWdrs7xbkYDwamK5okMXF8UuYk4Njjy+jwjPlhXtCTrsZT3A8UOeORiJKpN4cehs7kL79/Hlr87WFYnK44wJdaNQyzzjvsLcgRGiBdX3feNkn6a+LrHhL8WIhyBBVf+CuYeh/3Hp7QaA6SsCXPQzVJF0q/MPGmmFd+JhiJ97NBlj/fFTThPkdXerJiZHn0SJxwir3eslUF9hO6OC68H9lbqEpPnduT1r/QAqLMHKJ5w71WxOEqrdaRv6NJ/mlrhIiMxiODFpCIhJgtuUkwnlFAMLgeoLDgXaJBqbBtWkSH8k8d8RJzw6F6JBzxC6qHwPE346OBHdqXb7dISKYhKTdodaZuOa6wkuWsvDql0xvBO8p6RkYFsHBqlci6MHEcDB54AeHgH9lfAAWnQnzuLGT3Kckaq6HBdfeybfNLwO4E3ursu9YrI8fu0bciA==
  template:
    metadata:
      name: cliproxyapi-database-superuser-secret
      namespace: cliproxyapi-system
