---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cliproxyapi-database-user-secret
  namespace: cliproxyapi-system
spec:
  encryptedData:
    password: AgApmmgb+A3AHjuVkiBE2JeTUYGFtNJGy4afXAGmJCRjHmjriikiFewidjM8J42P5cEEH3kSxUhxl3cdFBaagXTcmTH3BmF2wElvBaQtk7QxlOoREOTIIbVzv010ywEk5zydshSeQ30OPmmg4fIDIZqNw4RGDqRzwzoYJ+gnhlE5FXXBkPC6ww3ssdETqw9d29WdgCaxhH0H9/NHfecIMz0D/RyiuhfdAWwXX1c2FsWOm+qf3dVsAKb9kWKKVl+34ImdQJJ88QP4oGuzOeypbMCvrjnS4hLkAJrX68RyWXnRkGqrWyoKM0bK46gTM0W+YmtM0CmxlmEOopE6IA92cO9RwAwk2ov8/1HMIxBdNv34E+Xp7qqp9+gPjYJjSl52G9TcMND+kiWx1JsHCX/HaJQ3AeHDxX+LuwXAPtYexMYqU5yac+2Vaw5FJ1mEwv05C414TmgGDsui1izpSP2h+O58W6x0M315sqR9K6H2qvWRIl3jyKd3Zn5qRbcxlI8nHsIw0JrlEM1g5AB8useYldF55mzuFJda3+6nb4L8g/ML51CTCscCjsJ6ybtvxhTMlLhcfol1I5y9itwRsIF3Potu7a7bCUrP53lt3AGKXXtB+iQye8oVVPdV0xP17ylwN/mmyTwmQF8rYhEIX8wi20BjjePjEXd2ZvYCSWyz5sRJ5eJzGF3p2QUBnBZCHEU8RXBpihGQpa4+ydDrnUF7bus2URQ2cO0d7xkN8g0POafR7g==
    username: AgAhT4IRk09mgNT9UNfy5hR/8b1XQ5EkShQLuhesTubvJDph+T/KQR1wDlzaSIl98ZaXj1kQkRX4IXDIWyWCyMo7vU/IqY6b8b3xzgMFm8vUdQ0fzR1WqU24hbJiEW2kCxJ2Vf76Kmg5vOfkfWa187XT37vjHYdDIAQ75dmI2A9jpBv1kMAnuCKB/Fsgi7n6wOiC/EUkdp2AOEqOIQ19yx8EegpWxk1QDWmIZq6o7lMVBRtZ3fE9YHJcZYaQMhN5nx4NNqqQD+67xTq+QCuTtCFNokouTbKEY9MunCYi86clYXuBynEQphr/4FgZQpShfynEYEIJy0nw57ZLouOl2hq0eaAEUidH/3hCo8yLlf02jJ/TT9JHHqKGooSkqK0Y7TSqIGOt1uP5IQFCXHFkrT+I5WGHvnpuRf5gWAxbafIvawBvzBFI0j7gz9PLfSI72TnZi8l5Z0aZqNJvAs1atZI7F2BQ//n1JcGDQ6W6QE1rJTVPjdMhFcjicckiZKZ/dUcehAA0Uw/WWZRzcQ/XnBYSDQJyZggQjDQVLveei5Db1yHHxIV0Hx5JlTNtq1nNKVCGTFlZ0O2FGw1ZmK6c/gexTp9KQ+fmSezb0PZ9BKqNtLDYr+jy/KLvlLovefbuxGfvThoyE2TyKq4sEKPtTyuHhEVgjil2S8PQJNPF8BqR3+JRnZlH4LWIxKfnJWaV/XnBEM6FA/nQ1R69OA==
  template:
    metadata:
      name: cliproxyapi-database-user-secret
      namespace: cliproxyapi-system
