apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflared.cilium-network-policy.yaml
  - cloudflared.namespace.yaml
  - cloudflared.secret.yaml
  - cloudflared.deployment.yaml
