apiVersion: v1
kind: Namespace
metadata:
  name: beszel-system
  labels:
    networking.tinyrack.net/isolation: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: proxer-system
  labels:
    networking.tinyrack.net/isolation: enabled
