apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-load-balancer
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/cilium-load-balancer
  prune: true
  timeout: 10m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium
