apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repositories.yaml
  - kyverno.yaml
  - cilium.yaml
  - cilium-load-balancer.yaml
  - system-upgrade-controller.yaml
  - k3s-upgrade-plan.yaml
  - sealed-secrets.yaml
  - reflector.yaml
  - configs.yaml
  - longhorn.yaml
  - cert-manager.yaml
  - metallb.yaml
  - multus.yaml
  - traefik.yaml
  - traefik-external.yaml
  - cloudnative-pg.yaml
  - backup-cleanup.yaml
  - mariadb-operator.yaml
  - ot-redis-operator.yaml
  - cloudflared.yaml
  - tailscale.yaml
