apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/monitoring
  prune: true
  timeout: 15m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloudnative-pg
    - name: configs
    - name: infrastructure-repositories
    - name: prometheus-operator-crds
    - name: sealed-secrets
    - name: longhorn
    - name: traefik-external
