{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "tailscale-oauth-secret",
    "namespace": "tailscale"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "tailscale-oauth-secret",
        "namespace": "tailscale"
      }
    },
    "encryptedData": {
      "CLIENT_ID": "AgBDVebAkp+VMxU2s7nrhjQPh/cN0tiNB4HRJV/1NXVI0qqUFrPpV+fkUGeIrd+qvmtUAHU15R7vPM+s8VfcQcSQdNoJw6FKu6TFZgxpIx4PCltlLhGp/6KmfmasdR34hYo24UcS7P/bbUDRFY6rOYn4uT0O8DG/rGuaYbiUvVSYZZ5ha6pVTVhPxdOE35O/VQa4S09k4gDF7I5aYYtJxcQNt9Zl8/ehXicchMQt4d7BH8LqhcFS7yemulThtGYss+X8SspzFXITNqTAu0zK42WNTnZGwJG7GlwWPwgxqrE7iUXCdKYhvpSbt+ReyynL4FhIhn54RbJSUNsDiXIFq3A3/wYnWLRHDwJx4RWGFTWEbFS5nLI9b8FxIsi/PIEv3eHHDBz7huHLqRC6lZBmaDjK5EEDiJP/CyJ4mmbU4iideyemJ34PHOoLqqe7ygKaBUslHxT2GB/r21ysbjOV8C19G8GFTlj0QhyFhXcPE2SGy19P1DGo6DmxSndFR985c0XSAQ7CYBSC7mGksugVqHM3vEDsP/CApCMzzYQaSQOCl4AcAdKeMloL+OOd7WRnT5QG0PXQxIGE4Q71x4zH0/kBLuCqSwOE4EqNORlVEc0igbdC7XhOMFR4Pfu+TOxOLqp1NMVCzgediBOphcmGxg2jP/I0ibxliGiH7P7bPiUkM4WYKLitrw+VEMz1D1wnIaM+VhFiQpzilwALQheLXapiIQ==",
      "CLIENT_SECRET": "AgBa3kLOTWM3y1VaI08QVnpKCvmYy2vQvz/wAsSRsDvhvGi4tcR0bsU1YB5OlAfCGVL6GSO3B6rQ1fv051AJzsGAJ2fOs7ncSUf03+MllcWR4agfMyszp7pDcrSYEvdV/hAaczIDFOtLoTYgaIzb/vFURUFEirU0AFZQZoTtW51JvYUT3IzT43uG+xd9p6mmMnWGuySTVrvcbXsCXhrQCn71CPJT6V2kpLKCVRU3RyXVKTW4pV5J+JjEy2ecy7L3sjWqUX//qgilOS8MjDHZFJnqfm4HGpsx5MUJ3/uQNhWQ6CcTQKytKZ8RU6nbEZlB7xDbKhCnFnJCePzeBsPMhoDgKOZATcsr+u38qLRZnf7r8FFycMSIiQrJ99eeea1qpahhh2vc29oKp3/qGVDIdwK5gURlxPlC2bXgfciYb1GpKMicSUtACnIoXebwJfiHxX5Td1Is+LmHExNP8DWoZL3K2fLZsbam+GkKajphCC1lx+PWMWu3psFjEG8exP3k+TIiXlY6AQnJEiZLzoGZAYUKIjm0IqSpOe1aZetx5DPOzW62a/mgIfyMuwhrH2S2a6C+JPKW3gKK0WVYS/MufYmy27D9MoRWh8lbnzKUbVEt3PiIKMH/ABv2jc8aFQ/hnnKzar9vx/lzucDHR548nzWc3GiJ/JHbBjGYMxyRNWwwVCbUNWtafsgD4AILseuuqbi/7+qc5LWLrKTSqWpu8KG6KmBcO+1+bRTnAvJZtagK+DYQPC3r3fPLXjLMgEoXVPVDJv67D7hRLbAh2HBSi/+m"
    }
  }
}
