apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-storage
  namespace: karakeep-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    recurring-job-group.longhorn.io/longhorn-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: meilisearch-storage
