---
all:
  children:
    k3s_servers:
      hosts:
        homelab:
          ansible_host: homelab
          ansible_user: homelab
          ansible_become_password: "{{ vault_homelab_become_password }}"
