apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: issuary-database-backup-store
  namespace: issuary-system
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://tinyrack-homelab/apps/issuary/database-17
    endpointURL: https://storage.winetree94.com
    s3Credentials:
      region:
        name: tinyrack-homelab-s3-secret
        key: AWS_REGION
      accessKeyId:
        name: tinyrack-homelab-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: tinyrack-homelab-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: issuary-database-cluster
  namespace: issuary-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.11-standard-bookworm@sha256:e8ffaff9d17011fb71f264d857c3b4c54cb86ed0443a4ecb0298cb96be708d4e
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: issuary-database-backup-store
  postgresql:
    parameters:
      max_connections: "500"
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 32Gi
      storageClassName: longhorn-strict-local
      volumeMode: Filesystem
  externalClusters:
    - name: issuary-database-recovery-source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: issuary-database-backup-store
          serverName: issuary-database-cluster

  enableSuperuserAccess: true
  superuserSecret:
    name: issuary-database-superuser-secret

  # 재해 복구 시 recovery overlay에서 initdb를 recovery로 교체한다.
  bootstrap:
    initdb:
      database: issuary
      owner: issuary
      secret:
        name: issuary-database-user-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: issuary-backup
  namespace: issuary-system
spec:
  schedule: "0 0 */4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: issuary-database-cluster
