---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: issuary-database-user-secret
  namespace: issuary-system
spec:
  encryptedData:
    password: AgBRJ6pmMOpmBwYNtVH50sYodi5EWVCXZ1VxfCFRCMpiIyggRPvMadx9eyWGWoDHIwRmFfizhvjw8Zxs+eKr9rvaz+1D6gRwkInQHD9CHctquYj3QG03aKiQgDV4MiOBzu+egZ7WcnlGdpSTL/t0BAqk6BcxTOJ3Jms7VAoCP93heGCJ1pmaRINUS2GMixxBVWRGgiKrBPVDtgwwKhmQRpTaMdEj9Co7MvMqgP+W0zCljfLTWMZIWzTz/7GA0a4U6eYtyKQH8Aludd7XwxV35QIUg/MD1Szmr9wcZnmp+658ebq6FwPak1dLPtY6xcfqnyYKyT0C4jVW/baYz/xqkV4h/J5PBnq5oSm4VJogpdodlxQK2DKL3IgNbdFaFsOxWf9IcDk4Zjq9DJ6WOUG7ZWv7eKzwFbbBJHE20htkj46ttX4TIrkm6ZXcnJ2ggNYa0x2V5gvJpG+yQ0tUL3JLTRHOvImTmigk4odgi74RLCsU0uUYDPNli2O0kY5/xYQ2fGF7YjVNYUKP4bOQlzOLnJp/oiionJ/bDkoqgQXvoZ/acSL3YhKNymuX2iuhc8Iy4bO4SoOzuEvz65wb6N6WyUSiAnlcj9cPELSIcUFZP692fbzWQIUCM854k1yiao+KD5D6owGfQ6MbrBxx0Ags0xZ43XrXQ3b+M4IH0GUAQ0DiR4dinIN88aG0YAMIrM7iP+op+SSa+Mioh8wQe1+cTQBnuVCncukdAvGr1jpzQQC+u+qo5YEJ013ObNJk
    username: AgA5oApFmKm5hj5bUOfyF1OjaAvYQF5H51TOx678p0Hf2GppXrEoR/trY13HsPQa+sywSKdHXMxkaKCJ1kULimcoJBlzmNJH3VoomxQPlnQJuyu/Rs1YAQ4rL2mItKTDknu6p+R5dPr/+82ScNvfNR1Lq8XxejrGjacJrGb4Uzr1dmusxquPZegidH8Yurj4wO+f3pCX+tDZmRcpEcpod4QamcHbz//q+SVKLSMURcjjeR0D0WOWY57KlJIwea2L2OdWSOCfcweABp3cHKYvMe5RQtHdl1FaDiJaZtSraR+edyWxNbs50EEtHPoP9tpvI0CyebY5OHjivDnndcYpk6OZ2lQwu8Si1LckddJgJ/C70xj5NkFiCUVJTurmaPWfPydhnwGpmlqnAoKW5ki8tiLag3YNEFW5uKR3twK1jtCKnC3Evr3ceYh75/NvPxV96WsYEGrcmP9dtrk5mmr4SVVPmZKI6Siyz3VmzRwtny2jfuax6Gx9hGwZtIEsFiJphLL1brPHQkot0eRh8RUl8wJ/wgdeKXQxWSEPMR7cyENR7uvHNdIOmoF6YcLVF/SQU/o+R2DjoU59W/8OcaPGaqy84IjZiTT73lq3fvQFIqYPrBvFt+loMBOnh70z1eQDfbKxiNW9llx3K4K0R60rZUXS5MfBJjr6c8CwMlnAbzHaJkkTraYnImI19KT1bhplm6W7aKZQabbe
  template:
    metadata:
      name: issuary-database-user-secret
      namespace: issuary-system
    type: Opaque
