---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-database-superuser-secret
  namespace: tinyauth-system
spec:
  encryptedData:
    password: AgB6r3exjR46mIrrsFhk5KSnb98TG7GCU+vxc7s7u7X9jiZEJxv2Du1Z2E8RRYruH33ohUMXsycmjWv+eMaE90P7zipzKK1GtkEAvbOyFSPLf6n/clYlH3JHMHkaAafMsjuIX71ZAoBA8WUbjXNdmTur3BHj8negBEbUU4p0ww1Xa5M5zKFgj7tmSQBq4VRIpxxEuK3wiuu6D9e7iczeWOcKSB7PrlUFAJOKnLmU+B2a3tJ+Yq3n1qwgwSm09xkeUilnSOxPJbi4aXKXojErRK6nsjyqTXqYnlpEStK7A2ZWEuzkaZdGhrxp3NyT6AQ4ZUF6nC9536AaJKkVOEl6/SMx6L9KP0QVqrOJWZXU/xzrVWLarE3NyW7kaID1s6wDqM5KgFf1GsSUS2UX1VG5h4/Ds5oatEAk4jAN+ibACmIy6XnRp/Ni8t4XqlqIc/P5HrhoOG3j2fJOs460XkRPLanZ7hgHy6mNT8Npu7Rq8D5VjuhxmonCNoGs+MB9V5Dika1Ytk9pXwkUdSJ4IaFSf4vMCeNEYR1E5vfU8tKAoD3H8B7k+/0C2KcYf8yduZt6y0a2ZHHCX2KRKZzS23/gT/3UR3bAquLekECnKTXvo3LLLlJd5uksrGaPMKzwApujxxKtfavSaGyWlkj8oKf8M1sOQTLW7fByhxJG4ipqpgT1a339+VJSIWAuR0aeYMnHnPWfhn+3zCYSLW22JxfDI1mRlma2b4mZtfGlXjNigRVtP3nwSWid39+lawN0
    username: AgBqJP0N5Gj8AuK9WTd6S37Le+s2ftKnb9Q5z4dpbUA6c9+KOthBlXvsx7RvF8oEGlpYeiGoCm895COIFspgdOFXjXzqCTqkSygvYAXmd2QzQg0cwtEQrOUEsewwTNfR4U/NF7ehShCx5DZQCEKSIgRfsM9ZHh1cVkv2QjGTuIfQUsmFj2sb3X/t96RFxqK1Zz5DvT7b/b2LGjcuwAKO/rrPVSOon3NQhCFZaC/aPVdGLBWDYwIkiEyInnU5MUmzUIIsqIS4O7MU51wEZjD2fkaGOSGPGJXc38N0PnAtXvT4nDDRqyosQ0wP7RFJSzeTUTNLRaBfiLsZBsWCoEhnxLEY9WnGWd5DK0Jp4vWsjexStL1Rc+B+ieG89C9UuldpqvM0xXqqxuCTZt8yYCH45ZpYRSHUkRxlKZXf3vcb6n3bjiGX6LhmDIW6npqpeaYBiUfRJqU+GPBHIUKKucFgjqTesyJSbRt6Ti3xZF360nZxiQwa74agFNwJUIhVkEg3sUuM9ilZnnac9Ng5tLNos5vOuMvfKmVjWoYXVWVKo0QBWlOA9e2aS8uVY4qUJ1UnfL13KGADOOpCFggDMmFYDCxJwXcPC6CQYwmYcgcnz6k0lKPpUWzHiVcKQeKf6yBm55Y08PnN7IlRa++F4IDmaj721frexHKMI5pGYqTxx9viBjl+1KSzCfb1akJvwtvvVPj/ulk5E37bXw==
  template:
    metadata:
      name: tinyauth-database-superuser-secret
      namespace: tinyauth-system
