---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-database-user-secret
  namespace: tinyauth-system
spec:
  encryptedData:
    password: AgBH/Jh+PJeScd4iItuGKdYjTFZ5QAhT/xvdg7WKP0ffno39qke8AQgQnLFO6FHF2RaDUtvJiOSXVMpOpmxQa25ohTdVykU7LqnzBFMepjAPqVqurr7GWcm7EW9xyQS0BV1RfHVsTv7UXlCn2svLy4/Ene0rJ8rxq3bao78EaupuLU6v8S+D85pbyTH54WujCqtW75hNBdhrhANXBfTdfnJUhAgS6QFCkkLIeknSnhtv7kDSM/HzKVmDDCO8/T3auSo9sxOCxNH4vmNPfsvz0pwEizcxOt+l7kMWxuOBub4gyP3PhNVRBfNdwZKs/k8BEitJsazOlrxnfzUL7EEvWxNpiy0ZaT2nCKxw/niTg6ePvSa311VXy/UqJMQkFpMI7o+1SNf7iEw/evnO5I4paJzejuc3vty/UdRoJTZpS9I/mzIr8ZuHjDSJu1KX6+BcbZST/MK/5VtP9G8T1Qu/IEjPnbGyx1tDXCD8J+i5vPqZoEm25UNrnQPdKdYUNjPJv/moXRV/+io44AzJQEuq0wuDvU81v5Wb6o/EGz6sdq90fmOYTh3BuuYWypR42pG3DQTJnDCTvjeIPa9d27cO0efrt+WDe+SEmoQTytzboQniWYoWJ8LzkEIQXKIwbn6r/35PgYTenmQwLxLxqWfMbN4RwFu4b+AvoYuTKcy5XC0Xfw9HZoKA4w4vCJQbGvjL12w5WpgRJWzPhe9GpWW2ENRq2dnpDG6VKePKNOYeNMPeylM19G2tZSWSvnqi
    username: AgCQ8fILKattCYe/4Z0NoHmcFVIJmqyhn48I4c/c0DRJq/WqfndqcZpq4ctG+6LBrcrgWTmvUHkeINQWtVTBMbdUahCa5iJ5PQ21yBgPpmJ4p++FNwL9isTgmffOK2AuTePUmyUvRuWfvkDDp9VlEMz4RiaK/H0AxUfovG1cVKRzX+yQ8G5tUzvAAdSRBYwmDaBot5etPsnAhY18pHYqPvFQK43bHpg4BXmryNQPLoBGFdvtIVBSmAk4FHIoeyXvpCfvjT6CDVOizLWpWcOiYWqcYHzDTqm78vcPiU2hOUwGpaoitc9J9pt+55wHoILcALZy5PB68vwn8+9xnfJRTW/cJUgVy+TR5H+xBfotgFSo7Da7bxNsznSbJdEtUgOuP8PBDeEuY39Qy3RtPPaYbmFdNqVnjUJdy4YV8aM7GqqS0zdseBqtP/8+MmWBWkbDKpv7HKYtetQ8Af0h8+M7DkqDBqqNFGrluhtonsXAS51ryvDtOeDgIYhc3BkeIFcSX4QtoyX3iH5gEe01FLFHKhsgYQhBT/gL5X0zr+/+gCn8JLjJeXreNXpiksIMytY1qWr155Box2093SZJOQo/obQsXBM20iRBN/N4+Ujd11dhVXBkrSD6gwf7JHQvvykiMmALsaGlcH9w/wcmzgNdvzdzG+9TfgHRS/fwBKoKvimH+0g5RVjWPoo8NOfFT2bz0F022oWjqwIHew==
  template:
    metadata:
      name: tinyauth-database-user-secret
      namespace: tinyauth-system
