---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: issuary-database-superuser-secret
  namespace: issuary-system
spec:
  encryptedData:
    password: AgAHIIkRRypNFu++jdubVPAQoyL4D3ORBcLJ7h7FG3zSQHxMUc8vPw6AQk4TL3nd/A3udz7ZTl4l+37z4iZHKUloLfYl0svdtHDxlI6WJXiXFNxehr8p2Mu++O5syYWCmfG/4QdTF4mg4TznotOImHHdmO1venHi2m4ZIK2mvywsVVsVaHTcqGpbVZLGQQgiidUtqN9Dn8sjqgMeyn3yKqX7LWOsIX+zKbma7/oICHaA2xxmEy3TDyzKohnxfintJX5fMiW2Ti4p0lqpGE4/HVcFYA8CFYEhODALBBEcY6o0zHWTHYVZehiu1cuLf5gva0X9zC5GhvuMkb5ycSEHAI1rCvgaIUg0L/JsfXNN4fF40mMD0m8FI9iTU8qpzMzd8sskIBkXv/zlQ9R62XghqkCPl3bob0RmV8kKvZ1ZT0U0981ExgsZvh9abVFvS+CeE/YKat9yOe/x4Pppw+dG+OlHl2scK3DKIkbkPNsF7Ip1QhYOPo69s1y1B7ngOmfhRTtf14+Nt2aS+9TwHDx57tVFYSXnsdun29u5fCFVSuuyyjZGK1RQdEWVoH8PhveB3nQvShsF8SpUCrcMAZukmz4cVxY/yssTLQxj7pimPRGCc3kAMF8mPnkjsR2++yqJ43lhzUK/l/PinuxairjrwCBTRC8jCkaudQARl5Cq77yRkdezgAbW+1qv8LMDm4/KmBuOypeKhxoWNVJyehwLJP2n7C3zeYDR8zqRPTXuTcCpX7iGSRt1hJYRb3Et
    username: AgAd09R1mf1ASeITGCYq133yWYIqfwWBnMkwSN7oW1B6wowCKLL6M1tPj6QO/hsHU3WT0/9WRsUhUkEpETuqTA5oMuzYddz9C/dzG4t0VvyPurzpI87n6uQ3kROUqX+zeViWsKh8E5OfsxpuhndbLaOYxLR/LGuGlB5HIi5EtMEckOIJ4lKCs8GNh5VhNKHxOsFFW16IOoCo1RmlAQBFBwTnVV/MR/BEtDxyC4bkXUgrCT9r3v9p6RKTYC/+fk5W1T3YoXzNAomHOKy/tkz9aHSwbRIQ3QnSnsOYMybPqL7WCbSpfldAbMQ12FpCtqBFbi2R1b94kpoWXDC0wHsMNZLdm7pRNRQgjYlhG/8cnRrU0cSoz3BjR4bkusoacw827Q3gfLK7aMpGhWhCM9p1JPUJ/+Tj7BvQUqf07LJOvOjAKUUYiffKXyacy/gAwNuMpwOSIK8X5tzxoQ9b307DTtV/ko0FppNb4eWGIgtOllysOuvRqKAwD28IpHFG8KIk9FCWUuHdkDcfCGe0zH6IfvyOgXUpEwLfswftQj8Qe5Ar9YgLYEBTK4g8e/j5ZquaB6nJ0xw0/+k9ULMJGIOKvyv8rpKYLUcILSApkJdNsTZBdhPRFJ7XIK5P0trLkaiUFK2a9+rSKnOaC84ydzxZinRHrnAM38HBO/sxOWKZVpeDwobOkHldbwsiA+1psZPYPQhF2z5SioFU4Q==
  template:
    metadata:
      name: issuary-database-superuser-secret
      namespace: issuary-system
    type: Opaque
