apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: test-database-backup-store
  namespace: test-database-system
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://tinyrack-homelab/apps/test-database/database-17
    endpointURL: https://storage.winetree94.com
    s3Credentials:
      region:
        name: tinyrack-homelab-s3-secret
        key: AWS_REGION
      accessKeyId:
        name: tinyrack-homelab-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: tinyrack-homelab-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    data:
      compression: gzip
    wal:
      compression: gzip
      maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-database-cluster
  namespace: test-database-system
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17-bookworm
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: test-database-backup-store
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn-strict-local
      volumeMode: Filesystem
  externalClusters:
    - name: test-database
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: test-database-backup-store
          serverName: test-database

  enableSuperuserAccess: true
  superuserSecret:
    name: test-database-superuser-secret

  # 신규 클러스터 프로비저닝 시 주석 처리
  # bootstrap:
  #   recovery:
  #     source: test-database
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: test-backup
  namespace: test-database-system
spec:
  schedule: "0 0 */4 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  cluster:
    name: test-database-cluster
