admissionController:
  replicas: 1
  container:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 384Mi
backgroundController:
  enabled: false
cleanupController:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
reportsController:
  enabled: false
