apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich-system
resources:
  - immich.juicefs.secret.yaml
  - immich.storage.yaml
  - immich.helm-release.yaml
  - immich.ingress-route.yaml
  - immich.cilium-network-policy.yaml
  - immich.traefik.cilium-network-policy.yaml
configMapGenerator:
  - name: immich-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
