apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulwark-settings
  namespace: bulwark-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-b8b15c50-51fd-491a-9bb4-e218b4ff7269
