apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulwark-admin
  namespace: bulwark-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-aa754d92-80c2-46e3-8589-793c18fe9004
