apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nextcloud-repository
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/nextcloud/helm/nextcloud
  ref:
    tag: 9.4.0
