apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-storage
  namespace: nextcloud-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/longhorn-backup: enabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-rwx
  volumeMode: Filesystem
  volumeName: nextcloud-storage
