apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg.cilium-network-policy.yaml
  - cnpg-instances-kube-apiserver.cilium-clusterwide-network-policy.yaml
  - https://github.com/cloudnative-pg/cloudnative-pg/releases/download/v1.30.0/cnpg-1.30.0.yaml
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.14.0/manifest.yaml
patches:
  - target:
      version: v1
      kind: Namespace
      name: cnpg-system
    patch: |-
      - op: add
        path: /metadata/labels/networking.tinyrack.net~1isolation
        value: enabled
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cnpg-controller-manager
      namespace: cnpg-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: CLUSTERS_ROLLOUT_DELAY
          value: "120"
