---
apiVersion: v1
kind: Service
metadata:
  name: minio-external
  namespace: minio-proxy
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-external
  namespace: minio-proxy
subsets:
  - addresses:
      - ip: 10.132.245.8
    ports:
      - port: 9000
        name: api
      - port: 9001
        name: console
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio-proxy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik-external
  tls:
    - hosts:
        - storage.winetree94.com
      secretName: letsencrypt-cert
  rules:
    - host: storage.winetree94.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-external
                port:
                  number: 9000
