apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: proxy-photos
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.namespace.labels.networking.tinyrack.net/isolation: enabled
      k8s:io.kubernetes.pod.namespace: traefik-external-system
      app.kubernetes.io/name: traefik
  egress:
    - toCIDR:
        - 10.132.245.8/32
      toPorts:
        - ports:
            - port: "2283"
              protocol: TCP
