apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: route-proxmox
  namespace: traefik-system
  labels:
    networking.tinyrack.net/owner: proxmox
  annotations:
    networking.tinyrack.net/hosts: proxmox.intranet.winetree94.com
spec:
  description: Allow the internal Proxmox route
  endpointSelector:
    matchLabels:
      io.cilium.k8s.namespace.labels.networking.tinyrack.net/isolation: enabled
      app.kubernetes.io/name: traefik
  egress:
    - toCIDR:
        - 10.132.245.40/32
      toPorts:
        - ports:
            - port: "8006"
              protocol: TCP
