apiVersion: v1
kind: Namespace
metadata:
  name: xeon-nanokvm-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: xeon-nanokvm-proxy-service
  namespace: xeon-nanokvm-proxy
spec:
  type: ExternalName
  ports:
    - port: 80
      name: api
  externalName:  10.132.245.43
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: xeon-nanokvm-ingress-route
  namespace: xeon-nanokvm-proxy
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`xeon.nanokvm.intranet.winetree94.com`)
      kind: Rule
      services:
        - name: xeon-nanokvm-proxy-service
          kind: Service
          port: 80
          passHostHeader: true
          scheme: http
  tls:
    secretName: letsencrypt-cert
