{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "netbird-database-user-secret",
    "namespace": "netbird-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "netbird-database-user-secret",
        "namespace": "netbird-system"
      }
    },
    "encryptedData": {
      "password": "AgBdCPbQtXzSe6H+1BVr9ot7HwF8xtsRyefuwxiAszfIR8hxNirx8eG9FLVjqBM0Cg+5sk+s32riaESZ8JuBvUBFyfKnveX4aTVVzgSkg6neZPlxRt5UsSOY+M5M0BhCPc2yys5wCmfzrfzkyUjQszmFhBcqde0ZbNrhMyUxIDeY84vHj9sqPXKH7JBMC9uOyeyuvRWUjU4XAU2P2Z7Kgyg1M2PMAT6HPHRj3bK7/GXkXk9ApTMvDGcodfSSFfRHBjmnBwL+U0UJsUSXJm5q0JJ//XmYVSS+vfQbmqpsruTguGdg/JoOAcAymyh8aT5B9Sleyr9lq+LazMsLaq5jwy9rpZKj6cqHCK0E51vRhc9deSOTSHKUKx7WmtLZvB+3OcMEp8n0thVtqbGHEWTaBk+3tFItCDRE3Qr35UdZ96opJM5/vmMTXBMu+c9JXzFcJa+xAML8ZH9BwbAhU640fx/B+0e/fx/VqIQxKJoK1+TQdHgORDwd5vwWGWwVKOLQ1tPv45jxCaHe8TU9M9651JdcQPS1rhTOzC1yvjoX+2hQ9BHj2vYVh263Rq1J4rUy/dG5bRao+MjoSeXfeWtQymhb8UXzLWGfpVTokEdmKgvXvyePaG19cXIvAw3MW5q0cC2h7+3wS/9Mcgv/BsfhFhTHZcrasoqpLtFnrXmVx3pZuZ0PnNUwZit/kcrAGf/+9sdi3jb+u5M0brCaRgjaYtxXZeJRb8qAQlDNJxdGHiI=",
      "username": "AgBwXztx+CPdTFq7LcCWOHVByx5gz3D+Oc5Xq95wvH7O5b2qzoHkmFFDGZLAK87yBCHeFrQYyT5/FdAmBKRGpp8TJWVsGZ/+hIsQqHx1hrcW0z2oKugDDkGMWoLQnEjxHcDoXZW+QstnoewdZ2KpVXmFfMrkJHco99DDiPYKwYCsoSteQFmbcGTPHnb11VmCGNf3LR3mkiHoY7pWxkaaOuY98A5oV3VV+KVHAHKHqolhVBuIApdtcDkDvPHtEXGvUW8dPeA8mGA5dESG41GDKVUuZAzCQn/WnbhIJjWw2VoMpogcCMbJoERa4J30jQz1977Wr5pUGVeK8GKzWK+tUc1QtEqAph4vujzxeuoMJC3s6MFfVAwZwMLMHkOG2x17TFyBUo44FH0iSvubk0YIXi2MJmZAn8K1osX9E4knnzVCI37hUemuFaK7SpGOBOWRZgdT+hawzggnMP5oiC4udaka2c1DVQJWC0iPQQZl111vvgBTwo4eBGO6ztX2ALP3vLh7U16luuOQK2N/zUd1/ufFNwECjjwRp/DySqctDmoNTcG0N8qBuCfM6iiaLbs/zk3Zc/CbJAZ8p3IEgjAMXEwngw4KIvLdxCI+Ge5FuYP1sLJX2kj81xO+z/9wRth34WmUJRR6P0Vn+oi7Y74ROZhNCOxcuEPKO/LOiCZsbI5O0gmGLSV+gtkObxCp1HLlnvoTjwAS0IbV"
    }
  }
}
