apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo-system
spec:
  releaseName: forgejo
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: forgejo-repository
    namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik-external
      hosts:
        - host: git.winetree94.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: letsencrypt-cert
          hosts:
            - git.winetree94.com

    persistence:
      enabled: true
      storageClass: longhorn
      claimName: forgejo-storage
      size: 80Gi
      accessModes:
        - ReadWriteOnce

    gitea:
      config:
        queue:
          TYPE: redis
        cache:
          ADAPTER: redis
        session:
          PROVIDER: redis
          SESSION_LIFE_TIME: 2592000
        indexer:
          REPO_INDEXER_ENABLED: true
        service:
          DISABLE_REGISTRATION: true
        server:
          LANDING_PAGE: "winetree94"
          DISABLE_SSH: "true"
        storage:
          STORAGE_TYPE: "minio"
          MINIO_USE_SSL: true
          MINIO_ENDPOINT: storage.winetree94.com
          MINIO_BUCKET: tinyrack-homelab-forgejo-storage
          MINIO_LOCATION: home
        ui:
          DEFAULT_THEME: "gitea-auto"
        other:
          SHOW_FOOTER_POWERED_BY: "false"
          SHOW_FOOTER_TEMPLATE_LOAD_TIME: "false"
          SHOW_FOOTER_VERSION: "false"
      additionalConfigFromEnvs:
        - name: FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tinyrack-homelab-s3-secret
              key: AWS_ACCESS_KEY_ID
        - name: FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tinyrack-homelab-s3-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: FORGEJO__QUEUE__CONN_STR
          valueFrom:
            secretKeyRef:
              name: forgejo-redis-host-secret
              key: QUEUE_CONN_STR
        - name: FORGEJO__CACHE__HOST
          valueFrom:
            secretKeyRef:
              name: forgejo-redis-host-secret
              key: CACHE_HOST
        - name: FORGEJO__SESSION__PROVIDER_CONFIG
          valueFrom:
            secretKeyRef:
              name: forgejo-redis-host-secret
              key: SESSION_PROVIDER_CONFIG

        - name: FORGEJO__DATABASE__DB_TYPE
          value: "postgres"
        - name: FORGEJO__DATABASE__HOST
          value: "forgejo-database-cluster-rw.forgejo-system.svc.cluster.local:5432"
        - name: FORGEJO__DATABASE__NAME
          value: "forgejo"
        - name: FORGEJO__DATABASE__USER
          valueFrom:
            secretKeyRef:
              name: forgejo-database-user-secret
              key: username
        - name: FORGEJO__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-database-user-secret
              key: password
