apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-data
  namespace: home-assistant-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app: home-assistant
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/longhorn-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-strict-local
  volumeMode: Filesystem
