listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/auth/passwd
acl_file /mosquitto/config/acl
persistence true
persistence_location /mosquitto/data/
autosave_interval 60
log_dest stdout
