---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zigbee2mqtt-secrets
  namespace: home-assistant-system
spec:
  encryptedData:
    frontend-auth-token: AgAoz4flhkHtNdcJHwIeF/N6H58/fTDhi5q9CkZSIjp9RCATQZBCD2KfS+v52qb2iHQXFmbShxiXsHnOGJK78FCNckSCv5bStXHKzSY8MwkAg0OUDLGAizUsQCqUZsbnc1m4PZDaNBxWHofRnvMl9URcl2zFSYPLEl1F1N2+8NCJqQBUhedYPUCjI/M1bhCHabNINZgfzLXrmS3zF0d0KRL3I8PMOFz0p1Fm2oKnEJ2uRdXVxYWvZ5ik0Wrp/KhnBBZfS35Mo1eXB7rFU4bwG96AT+W+Fjq4G508WT9i49s8auPI+mexoCqKCL8XEVmbX9o2Zdqu2oXnIOUEjw1hBqu+4ZTyUmTVnJTKanvqi1HeFFV6oBxYBHQXJ7X2ZuENN+higsgqLoGJg3srVEThXPCvb8F6l/092Lvej9juRQ1NTwB6iWvlJcsyjU70MN5OHY+C8eCiSyg1y2qGHm+KtAbXf9s5XCDKDwJ/9Sjpx7RCeyP4NvJfTyTKAVSAW9haYEQcLxAo30K3wFksSlwYy9Y9bAHOHpJFaGfIfUiP14Ew06JwaGWbGQIYoM3hYVLM1qpEPg6+MZtYa+62ltDlyKO/Rj98CcK07dlO9tmo2Rrnzt9fMwmoAiKo7OkHyoS13rkt4/y2TSwrYs7DEkQlv9tG8V7HaOkzoMPbczEh/1Fz/ZlrEyXSkJX0ioi6Kc153iqd24CqXfv+keZm7kLic6r2IwmupVfYN2balZFGPEAMAQlIeMwyvMJuQHbHweUSXDT2tEXcTF1MnDvdjAJYcppo
  template:
    metadata:
      name: zigbee2mqtt-secrets
      namespace: home-assistant-system
