apiVersion: batch/v1
kind: Job
metadata:
  name: immich-migration-initial-v2
  namespace: immich-system
  labels:
    app.kubernetes.io/name: immich-migration
    app.kubernetes.io/part-of: immich
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-migration
        app.kubernetes.io/part-of: immich
    spec:
      restartPolicy: Never
      containers:
        - name: rclone
          image: rclone/rclone:1.74.2@sha256:0e95ae369f739942bc96bf1f1c2fac5c044cbe6ba39097f2ffcf979103a1a864
          args:
            - sync
            - :sftp:/srv/dev-disk-by-uuid-35dc6271-fb3c-4363-bed9-300cdc56315d/docker-data/immich/data
            - /data
            - --sftp-host=10.132.245.8
            - --sftp-user=root
            - --sftp-key-file=/secrets/id_ed25519
            - --sftp-known-hosts-file=/secrets/known_hosts
            - --sftp-host-key-algorithms=ssh-ed25519
            - --sftp-disable-hashcheck
            - --sftp-shell-type=none
            - --transfers=4
            - --checkers=8
            - --delete-after
            - --exclude=/.accesslog
            - --exclude=/.stats
            - --exclude=/.config
            - --stats=1m
            - --stats-one-line
            - --log-level=INFO
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: library
              mountPath: /data
            - name: sftp
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
        - name: sftp
          secret:
            secretName: immich-migration-sftp
            defaultMode: 0400
