apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recovery-guacamole-database
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/base/guacamole
  prune: true
  wait: true
  timeout: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - target:
        group: postgresql.cnpg.io
        kind: Cluster
        name: guacamole-database-cluster
      patch: |-
        - op: replace
          path: /spec/bootstrap
          value:
            recovery:
              source: guacamole-database-recovery-source
    - target:
        group: apps
        kind: Deployment
      patch: |-
        - op: add
          path: /spec/replicas
          value: 0
    - target:
        group: traefik.io
        kind: IngressRoute
        name: guacamole-ingress-route
      patch: |-
        apiVersion: traefik.io/v1alpha1
        kind: IngressRoute
        metadata:
          name: guacamole-ingress-route
          namespace: guacamole-system
        $patch: delete
  dependsOn:
    - name: cloudnative-pg
    - name: configs
