apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - davinci-resolve.yaml
  - guacamole.yaml
  - infisical.yaml
  - issuary.yaml
  - litellm.yaml
  - n8n.yaml
  - openwebui.yaml
