---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis-secret
  namespace: nextcloud-system
spec:
  encryptedData:
    password: AgAqXq+yccpXowrO4lRPJjKnzNhygTeiGZBvnts2Ul5Hm5SN1DeF7BY7nPhTagKB5inHUR6dwbsG2Otsi6Du3IRmTSJACPJbxobudGMCvz8hgxEVp++2hKmqMv+h4Go5gNJ+y/NqF2JSbjWARKIRhK+OApEAtfbUsVtJ9/gaZ7DuQgcxckPWnSoT/r5kOtVkDepy7/jugwAFrqRyTzA034CvBK7Vux7VT1IQZERt3E0NpQEvVDeBGbc7lwJLY2ysq6Vz/IqunglTGMlD//9lPbV8tCGxuHP1ta0f4ogk9uP0XHXi10bu+yGIoB95ZYeFelcyrE43RrJLVmEoWoZvxMA0NWh4TGsBaTnE9vdpqvV/+dzkQy2v/FNtyCAeXn3CmrHeNMiPaLRpfmtganLpZamQV8UDxg5CeJm5zq7GOEo7vBWehBUWReV3TAUxSDuKouR1QQl8huTRTiJCFtk+qTr891zNoJ2/grC4VKinwTGyC6mUNiV7ROOJXq5jxV3Avty4/99tQcT8NMY204LJDnXeN8RPOVrHKRYVKHYyoI8syeLz7qbU0uvR6nms9MD1BRVzdn5XbbmYk3LQiQY4sEAMAkIftTOBcQpEMU8fbl9ZvvesSisFxmz/nQPhv9tn3BYOA6U22EJOnjPlXm7bqmi7wS8RSV39nvs18HrlV3p2aFFpnaxNzLix9efBE3SJjmGu1U+2ojFUiNnOruuk4cfEIqzAD80KP6K0TKaNeYM=
  template:
    metadata:
      name: nextcloud-redis-secret
      namespace: nextcloud-system
