apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proxer.namespace.yaml
  - proxer.secret.yaml
  - proxer.deployment.yaml
  - proxer.service.yaml
  - proxer.ingress-route.yaml
