apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxer
  namespace: proxer-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxer
  template:
    metadata:
      labels:
        app: proxer
    spec:
      containers:
        - name: proxer
          image: ghcr.io/tinyrack-net/proxer:latest@sha256:3aeacd9f7d28bad8410659bdb4223c7146772b10e42fa415db7a947d0af13d51 # {"$imagepolicy": "flux-system:proxer"}
          imagePullPolicy: Always
          command:
            - proxer
          args:
            - server
            - --listen=0.0.0.0:8080
            - --token=$(PROXER_TOKEN)
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PROXER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: proxer-token
                  key: PROXER_TOKEN
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
