apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxer
  namespace: proxer-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxer
  template:
    metadata:
      labels:
        app: proxer
    spec:
      containers:
        - name: proxer
          image: sha256:0c2118feac0251556d6874eb7d33790630273b4b28b6139f23167a97403f9a80 # {"$imagepolicy": "flux-system:proxer:digest"}
          imagePullPolicy: Always
          command:
            - proxer
          args:
            - server
            - --listen=0.0.0.0:8080
            - --token=$(PROXER_TOKEN)
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PROXER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: proxer-token
                  key: PROXER_TOKEN
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
