---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxer-token
  namespace: proxer-system
spec:
  encryptedData:
    PROXER_TOKEN: AgApmQK2yvUtoXmMbZp+C7KHXDN5qsyVrqh+pnBa1q0mEvhhC0ujqlSkuMOyUHfb431U18cI0Ewmef7bS8PCOrH3v/NtJVVuqixVyo6X54p7Rc4XOHBb1Q4cDHNJIcu194rhkrM/NVANQPMsopQKMaOknjHUm6UQ5ZR5R6KlvaPAti3pUZ7Q7kaB6p1soOEonbRwqPCCGtvqbWeKxaLgED0JdMbR/G5ZEeFJ1iN3+PRr9NlcUzjpmgwvZ12QMruGQ0S/to6kSkfiAnmtOcYmE1/KCbKnvGvbJtYFdu6Zya6Tmux2iyI25/nS0f2aAijWQl8ZTt8d45KauOfZMi0n/VGqblylZ6NXUJa7dfadyUC6JN78Lwy0PDYVsCRcP9OCvLdEm4A4Ulp9JbGPVBZP5CvPEuI9zVkFJLdOHkICcK01AfKeVYCAHVN8hKiQvaWRlNMhG+MeBn/hP2GtMdyzyMFSQwkmE9u93bCPih0LKG5K9UVW+quIZICLHNhDj87DegmdO9FOXTsXat1ABpupQTYBwBrXNs36ZslCbjqkOXXL9/ZESiX5eSCUe4UjKC90GRY1ceT8t4zzJOQV7ml/b0u4uMYQ7USiY21lZIFqS+QLc9BusUEL0R+5ki/PMmFuZOZrKeXlk78/p2QEbChZm4rpfTlm7aIlgC3ynrmwRbDpIinPg8TBOaSSuO9KPBNOfYH8IVZ9Z/HvKOddc4aPrnUjSN8rjDPF6C+i6kECdRediv4hA+zAiqtKLjPKiXK6ttv31j9Eus+IsD9GRvw8xwu1
  template:
    metadata:
      name: proxer-token
      namespace: proxer-system
