apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxer
  namespace: proxer-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxer
  template:
    metadata:
      labels:
        app: proxer
    spec:
      containers:
        - name: proxer
          image: ghcr.io/tinyrack-net/proxer:latest@sha256:7a850e614b825c176251860098119d503fae8310dd44c3cb9d7ef16001f2e781 # {"$imagepolicy": "flux-system:proxer"}
          imagePullPolicy: Always
          command:
            - proxer
          args:
            - server
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PROXER_LISTEN
              value: 0.0.0.0:8080
            - name: PROXER_DOMAIN
              value: proxy.intranet.winetree94.com
            - name: PROXER_TRUSTED_PROXIES
              value: private,loopback
            - name: PROXER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: proxer-token
                  key: PROXER_TOKEN
          livenessProbe:
            httpGet:
              path: /__proxer__/health/live
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /__proxer__/health/ready
              port: http
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
