---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: kube-prometheus-stack-system
spec:
  encryptedData:
    bot_token: AgCILTXn/gllFCj990/pV4otMSslbgRKWdjsiUbdmZzd8tGTu75Utujk3ZAjsGvnOcDZ4/UxISD2E7T+LsIt8OXCuPwn6uruq2B+ScQBhNccp68DAofukNgGtnx3qHjN9OPRqH3QOXeo4zqSx2WFObmPoqERcvDv8r2FVLcfQOgjMccYKB0gFTxIQxqMZ2Nrq3taaxhKcCGbS+BzWKfyFpmlAHOQEqt50SqbFsOZkyZY8m1mfwBHdvpDTZUpkGwt4mbPbxVSU+4E9+GOkAsEZ8CuynLHLMfnsYHfFzdBeNyL1nJEj9o4xHsGDACbpdp4sXBxqQ4BSx6yiefTyBFn4jcBynvRXU+paYtuD5F7wouLdV9ByYrcgUvAGdLlIDlREJrlya1vQgg1eDYdla879NTgY2qrYTjcZMfQNL8NA2LOY6jTKU8LxSOtfBkS9A2SBHGdTZFBuQ28vyDwuzwsw8cS6Frd5a3GcqX40r6R7IYMg+z9QIVGcb2Ab7KVesxMGfDyzU3qD2JGVsPlhpAvZ+XkYbE/FNATO0xYs+lrrJ3MHqEpAiDLlrKvthL1ZCAMc8zHcfDqUyhuovxtxw59lxbyBjXM1Vo8qRmtf9swYGTX+apMOxMeNQda9RZV7IfebCUb+j+5c6IVqpcd4XqjsRPfy4DsjnkrBfeBpHlM18hoLzp8xD1qnb3z28SxxMRHJgwiZC5biIsdKcIXhCXhfQKqYuoCS9+rwr+I6Z8O3xcsMJXITlMVCs1AW7HBZ2R5
  template:
    metadata:
      name: alertmanager-telegram
      namespace: kube-prometheus-stack-system
    type: Opaque
