apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - wg-easy.namespace.yaml
  - wg-easy.network-attachment.yaml
  - wg-easy.storage.pvc.yaml
  - wg-easy.deployment.yaml
  - wg-easy.services.yaml
  - wg-easy.ingress-route.yaml
  - wg-easy.cilium-network-policy.yaml
  - wg-easy.network-policy.yaml
