apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-data
  namespace: wg-easy-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: wg-easy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-strict-local
  volumeMode: Filesystem
  volumeName: wg-easy-data
