apiVersion: v1
kind: Service
metadata:
  name: wg-easy-web
  namespace: wg-easy-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wg-easy
  ports:
    - name: http
      port: 51821
      protocol: TCP
      targetPort: http
