apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg-easy-oidc
  namespace: wg-easy-system
spec:
  encryptedData:
    OAUTH_OIDC_CLIENT_SECRET: AgBW2uHLjGQJS1UyqpPGJinuDgqqAWDH2Cd+SvoTNqcenCMWEQ9N6bBuloX+Pgv3n18l/khBrVaCOIetS46nmkPPvp7jsKfBNOsi9NFBKjCcdU0ZkFTB1d2IrqNgXIVg2YOu8c37VwyLLnxcFAcI+DgU/8aywg3t8xGys0Zamq9ijmnwejMnbvePzRlo02r+MUAGRDOgrfjwh8fZqr1fIogoR80zTUC6IjKw8XRG2HVBMXDd6jO4Y/K92BA857rYlmGTfYuX5zybmvDMe59e1Sg7VyaKzu3O8gxxg+I52b6yTquQH+N+8s46k5+earF1H81T8BvPdCje6Gt7V/ADA6eNqR+23yWJwrC14LyocbKhfOxq1EPENFqJioHvJ5IcA5X2BHHPm6S2Am5uy3UIH+IJR0ntk6XKBlJiase3OHdhYRehQxHMlPO5dyXTcpd3a+J/utiJZmNUQY16Op01EbPYBCfC1PBe/6PGrqmDx6sSm44lRqZZVUL+XuGAFKCQgGChV9U3K+7IJbzq3xqpoxFjEuEHxvewlDhj7lLFNJDFLiUPaelL2vVF+PoYhF5QwlgICTVrUdqg8HkHZRC/R9rRqoD3Jo/2P6WpAymbrEoOedTG0Df43JNb74mIhkju+j1HPxwHxxKsPTxBkbdylKkCHNjP9Diks/tsGOMbi0rfgrowjVGx2pwzBFUl4Y8Wo61C5BL+2184rJBRM2Z1X3u8PelBeS5ocbjY+0dkeUfY1rEUPXxxanbuPXiAot7IUhT9y3qdkT1PUPgDrrYF0zQR
  template:
    metadata:
      name: wg-easy-oidc
      namespace: wg-easy-system
    type: Opaque
