apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-data
  namespace: wg-easy-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app.kubernetes.io/name: wg-easy
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/longhorn-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-strict-local
  volumeMode: Filesystem
  volumeName: pvc-05629bef-d817-4839-b569-4870e143b669
