apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - searxng.namespace.yaml
  - searxng.redis.yaml
  - searxng.redis.secret.yaml
  - searxng.valkey-url.secret.yaml
  - searxng.deployment.yaml
  - searxng.service.yaml
  - searxng.ingress-route.yaml
  - searxng.secrets.yaml
  - searxng.cilium-network-policy.yaml
configMapGenerator:
  - name: searxng-config
    namespace: searxng-system
    files:
      - settings.yml=searxng.settings.yml
  - name: searxng-limiter-config
    namespace: searxng-system
    files:
      - limiter.toml=searxng.limiter.toml
