---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-valkey-url-secret
  namespace: searxng-system
spec:
  encryptedData:
    url: AgAlqayL19tQeFx0pbiOZAip+4pqf8Ll3EMEs3WNBkegMn7jLuLLpEvnZ/iWebDy9sWSWYigS1hO/fLoYWmwEwJmMcj7fglVXSLsI1P9c00emmKBdgA2hVI0M16bHYGRRXeGgpWUC2N32QFPAl6rmKQ72ilqhfGLLHRnoW5B+opY/sDg2bh7LF7nA7PXKA1WE4OQLRsLJ2oz8ZWi/G4BFv+mYYvqGv+4+m5X3vYzjJK9WkqBSupSnwVfiICLmRudT3AN4Q+PeCIBxu/ChHqbTONujD+UFzpMvdszH4Xk368T00CvWpm+kRY92EWVsnXWZVN8TGhBa4GpcQiX6BMVAXd6afaE729j01e3X7dx1LeW74m76vslx/wStJOBGOaIxEFbI5jFLDPDK0ae346rcqTiSueyIEpPVS9OUqXeFCLt1L3TC9oHCm2Ig7jIooa6LqoUQzrDn0GoVmhNdXYlAvLRUyjy3de4lkP+XFzEklsW5aD8V82SvBsaeGxIfbEYtX/kNS1Bgh/eci29V2PYYNlzR+jHtC7jwDNToYi93m94QXVSrWlNVwCtf4TitVf8v1mjqzbzjt9SMWemMF4Ldjwuzt8zNYi7rnpm+s/qhaZDBm8Tdt6jxtNygTC+T+1Z1ynn13wkyCwxAmX32BFe3PG44XbEr8gHEu4XR/Xj2PvU+cRxXCq6tPWwmU9Z+8ikkZbEZsoTyvDSNCsQU2nvCe1mRO2/cPG/NzmwVLo8l64FGBqm8tsHtIM0WQVC2VDcieBJ8p6xu4og5finEM040AKJt/V50k4vf9eJgXjjqUASBXUO5+fXV5K+dJvwCJUXXCk=
  template:
    metadata:
      name: searxng-valkey-url-secret
      namespace: searxng-system
