---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-redis-secret
  namespace: searxng-system
spec:
  encryptedData:
    password: AgABw1xQ4SuQYezc1Lha81k/UB1nhRHnqnUSNcEHPmAXClh0G3DM/Dr39hhSLBZofBpG6mDkSwPdkYv2fFRNuWz1AAWsO59+lkmvMYwAyf+02W/Ux6zoTTppZ15JP19pMmwIIXa43gXqTW6+4V7P2euRIUu0dzGgkabJufW2FGSv3nBoO9mYZoFJF0ZPnAdS7uAWFF6z9Rwrv2BIjQQVK++NM4KA2h6eLbYVV2VtYGNVhbmC1RIgwIM50IOEhBIFzmw68NpE70jOmAvsHX/iUSVRlnna7ZG4X9OYmgb2ic/aO/K3bu42gU6kcaS3qrGTtZxBmSLX3GXTfWYB96QfmTTKWU4G26KaUIC3SeJe5kvwDvRVlgpp1vpLkIvGQAxp/QGp1xcuPM6i4E9IXuNxkGbdcI+JrduMgRtLg6deelQI1vDcG+NteSICq5Rbc/dIVnBwma009P8G1HLyf6B/i4bQ+EdojJmAmps/7Dlz4zkoMDFZ8JBocrCxr2hFjwcv1Xie1h6VNDxiDrPV7hI+X9mVvDOTZBQ9tbf+3OYi1R9pJfYYAGFs2rFbD2Jk0LWra8pSFYfEAX12PGF8502cwFZzcSLNbRH31YJW5uGLEXyBQLwtIkVYpwJpsnAGMauUOjR986Hq6vEZbuKswm7nxVHGZqLrmLEGr7YmPuXrkO7c6RWYxr0n1T93ydk/qz4VeR6bE/qb00DGWy2TIxvhi0Ro4RSRuxBF87bgP5knLwGGdA==
  template:
    metadata:
      name: searxng-redis-secret
      namespace: searxng-system
