apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: searxng-redis
  namespace: searxng-system
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.4.11@sha256:115d8e221b1459b9f2db7d927ed40318ffac4eb2cddb5702974bce92d32b7a51
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: searxng-redis-secret
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-strict-local
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
