apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: searxng-redis
  namespace: searxng-system
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.10.1@sha256:1ee437bf63f00a36d23f58ca576dc0c4e7e233a9c606959c003a14f39eb40da4
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: searxng-redis-secret
      key: password
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-strict-local
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
