apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml
  - network-policy.yaml
configMapGenerator:
  - name: opencodex-config
    namespace: opencodex-system
    files:
      - config.json=config.json
    options:
      disableNameSuffixHash: true
