---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-oauth-secret
  namespace: openwebui-system
spec:
  encryptedData:
    client_secret: AgA7OnkFANFU618jAPSfONfJrEodK6mg590SnQrpX4SPiUxuhH/k2ZZfzUKL4ZB3YVHGFdpZOZaSZxeU1rhE3uL77WuZaxFGH4GCtd9TgS6J/kecZ40Ff5yS9IjwBl1HRROkyvH7KZ5jHTCIU2WJ+8y1KepyfqZhEKUMbdpgwaxShVSpeKR8AoBmabJ0dnVPwvPchYZSG3MYsj1EAoF7bXvG54QtjMlTqCyXJA39uQ+i14dpNSQeWEfeIb3Co7nKU7YU2kdPwrLEjUIE8iM3AIU1kYQfVyXu8moUXQrglyJKIAS1EYz2h9cVYRsZUYq/6QxiH2aqcNAphMTlKoV7wumSPaHUekNQj0t0TIUhqZYWnYp1ID7DHP6AMWSCyUjRz5Mb/in0czZyHHkpbpoI0OtruC3dGaWc43iWbC4uO0JGDJN7mdcjOcdHtxIbaOyEVc5j3TG5SuPnXW4+u0NyrxEbDdY7dqOYdbpYdtcBgAGGOjzdDw6GhhTcikSff1fK0PLeffjwxfaZbiW68X5p3lITJDGNDc7n0yQrUPiyEO29zLIKeLUD4InJKPvuxd2n7nLyPfkEKZwpi7eypXXmMKCJfiwsgwWhlJ98uUDKhG15xNkzSUXpuHeNsc1bMjbJluBGbNBB7CeUDEaEndHL/9IOa0l3JChMjYi9z9LOrmVHKCgulWtDbdZMtnc49GoihXRi0WjvqZtqMwPCJVOOlP6+BWxZdgWZQDVsT4moGMwlMuvuGjzt8FTPRB8fMgL/8ZYVucMbusjeEsAej1M+ZIua
  template:
    metadata:
      name: openwebui-oauth-secret
      namespace: openwebui-system
    type: Opaque
