apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-helm-release
  namespace: openwebui-system
spec:
  releaseName: openwebui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: "8.14.0"
      sourceRef:
        kind: HelmRepository
        name: openwebui-repository
        namespace: flux-system
  values:
    tika:
      enabled: true
    ollama:
      enabled: false
    pipelines:
      enabled: false
    replicaCount: 2
    persistence:
      enabled: false
    extraEnvVars:
      # DB
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: openwebui-database-user-secret
            key: username
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: openwebui-database-user-secret
            key: password
      - name: DATABASE_URL
        value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@openwebui-database-cluster-rw.openwebui-system.svc.cluster.local:5432/openwebui?sslmode=disable"
      
      # Redis
      - name: ENABLE_WEBSOCKET_SUPPORT
        value: "true"
      - name: WEBSOCKET_MANAGER
        value: "redis"
      - name: REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: openwebui-redis-secret
            key: password
      - name: REDIS_URL
        value: "redis://:$(REDIS_PASSWORD)@openwebui-redis.openwebui-system.svc.cluster.local:6379/0"
      - name: WEBSOCKET_REDIS_URL
        value: "redis://:$(REDIS_PASSWORD)@openwebui-redis.openwebui-system.svc.cluster.local:6379/1"
      
      # S3
      - name: S3_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: tinyrack-homelab-s3-secret
            key: AWS_ACCESS_KEY_ID
      - name: S3_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: tinyrack-homelab-s3-secret
            key: AWS_SECRET_ACCESS_KEY
      - name: S3_ENDPOINT_URL
        value: "https://storage.winetree94.com"
      - name: S3_REGION_NAME
        value: "us-east-1"
      - name: S3_BUCKET_NAME
        value: "tinyrack-homelab-openwebui-storage"
      
      # CONFIG
      - name: BYPASS_MODEL_ACCESS_CONTROL
        value: "false"
      - name: ENABLE_FORWARD_USER_INFO_HEADERS
        value: "True"
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: openwebui-secret
            key: secret-key
