---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-terminals-api-key
  namespace: openwebui-system
spec:
  encryptedData:
    api-key: AgAnAEPvcqW8fmA2sT0tihUpJi4pTcN1YkQ9wD2Ozjw/YZ9ZjIDHDy43fFpm2Z9IHn9dQvtUw9B8K+Hz1yC7fTwy1T+6u2CZZGmbW1oHauacBQ4gJ7voQ5RmLB1sVYQWqFXtApnx/VxhEVOgHLvMnkf7nkLSL4tVHZT1ZOsYEFt8VZNow9pqKrRn1IReXDrfThrD3n2ZVo7d8d2glly9DYREWrD35iY5fY8G3X4fOgp1+E//vID9lIVFNu7gMgdB0Zk+t7ZGTcProIJJpC6T9mC9HjDzfrjPMasTKELhObokszVCfFHKxST7kmJFSHSXYAskcZQUITZn6HRl1n1Tr4EbuJrW5U9/z/76vxocdS9YxZ5iDM2tqYZHustji7n/gcLIAZppkHcZmejB2djDIC6Oy0khO0WzX1mnAlyckwwe15TPXgxepTLippHOH/z3E34wwmEnfQvd9B9DZip3AFRAdnD3Wydy8ktsvGksN2yBBMAZqWDQMhagyu5s8cihGqeAy8n4TTutsaVNP2GOBT7eeAL93nSr8gIF86NB+m24nCZtzerfUS8yFZS1ajeSzSXoGzn+ED2X3uexcTODZjcAh/LXzmVdxxlfNeh9Pi+aiQiopxaXJDVohq7VRGXJa//cyWPJVkG7+sA8e2jMc6upToUjG11JAplTSWd6CUF6HsJdpkvzhjxzinV4uMyCYrOy1+E9Q4lEk09J8WSoJ/voz4LKKnEeRylhUfYnfvS2leXPoYTZ8zqEfE4AWA89TB1AKAddfh2i8sOtRw9AwtMQ
  template:
    metadata:
      name: openwebui-terminals-api-key
      namespace: openwebui-system
