apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui-helm-release
  namespace: openwebui-system
spec:
  releaseName: openwebui
  interval: 5m
  chart:
    spec:
      chart: open-webui
      version: "13.3.1"
      sourceRef:
        kind: HelmRepository
        name: openwebui-repository
        namespace: flux-system
  values:
    fullnameOverride: open-webui
    tika:
      enabled: true
    ollama:
      enabled: false
    pipelines:
      enabled: false
    websocket:
      enabled: true
      redis:
        enabled: true
    replicaCount: 2
    persistence:
      enabled: false
      provider: s3
      s3:
        accessKeyExistingSecret: tinyrack-homelab-s3-secret
        accessKeyExistingAccessKey: AWS_ACCESS_KEY_ID
        secretKeyExistingSecret: tinyrack-homelab-s3-secret
        secretKeyExistingSecretKey: AWS_SECRET_ACCESS_KEY
        endpointUrl: "https://storage.winetree94.com"
        region: "home"
        bucket: "tinyrack-homelab-openwebui-storage"
    sso:
      enabled: true
      enableSignup: true
      mergeAccountsByEmail: true
      oidc:
        clientExistingSecret: openwebui-oauth-secret
        clientExistingSecretKey: client_secret
        clientId: cM329FCwUpqO55pUrMWRjj4abLCeFVGIm7D7lm3B
        enabled: true
        providerName: "authentik"
        providerUrl: "https://auth.winetree94.com/application/o/open-web-ui/.well-known/openid-configuration"
    extraEnvVars:
      # DB
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: openwebui-database-user-secret
            key: username
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: openwebui-database-user-secret
            key: password
      - name: DATABASE_URL
        value: "postgres://$(DATABASE_USER):$(DATABASE_PASSWORD)@openwebui-database-cluster-rw.openwebui-system.svc.cluster.local:5432/openwebui?sslmode=disable"

      # Redis
      # OIDC
      - name: OPENID_REDIRECT_URI
        value: "https://ai.winetree94.com/oauth/oidc/callback"
      - name: WEBUI_URL
        value: "https://ai.winetree94.com"

      # AUTH
      - name: ENABLE_LOGIN_FORM
        value: "false"
      - name: ENABLE_SIGNUP
        value: "false"
      # CONFIG
      - name: BYPASS_MODEL_ACCESS_CONTROL
        value: "false"
      - name: ENABLE_FORWARD_USER_INFO_HEADERS
        value: "True"
      - name: WEBUI_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: openwebui-secret
            key: secret-key
