apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-nfs
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
  nfs:
    server: 10.132.245.8
    path: /export/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-library-nfs
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-external-pictures-nfs
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
  nfs:
    server: 10.132.245.8
    path: /export/winetree94-nas/Pictures
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-external-pictures
  namespace: immich-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-external-pictures-nfs
  resources:
    requests:
      storage: 4Ti
