{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "immich-config",
    "namespace": "immich-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "immich-config",
        "namespace": "immich-system"
      }
    },
    "encryptedData": {
      "immich-config.yaml": "AgAqlh7yu1coox8aCnXIb+/WlK0fcZ/nftiQVBDGLFLGy4dIsypznugArLURYvJXBO4Irm4HW0hdOq8L190TwGwOEIQkYuW1BHaKtMpz6MIRSyCIEz/C5xKXoOb9Ok5owvaPTZYzc6WC46O8t189Kr+tH2MGaeKA5Dr0dUTZRJMAparbqDn3FezN/GOTsH2SaQmsP9Gm6q5QsD3VnSXpP1vS50nmRZpZyV3RBr19o24hiuNMmGgWBzRK3j4Z3ARpn+sRM9eKMqZ3Kft8L6/rhxTQ0v1Q+dZYgkIr6vfP7dldPmQQnXQxpz/5JIdxvCAGQ1SXVjMlxp8wlX1OGtdGalqUR4sAQaTFrnJUO9XHrRY3O9PDMIuiAMm/p4gERWoyTnn4FXVd1ajMF2En9Rce29H5bAw7pvml+WFOsRd7SUHcbOSh7AZbfY/nynqEedenCY0NYxAt8v09+OgYNwVqD1tnB9OAGvhJ5EmW7A/s68FZ6od0G/mBkllP9TLCLctlfFPsHHCiM2rsw/1geIlNQm7UDsS2UJerPurJTJAyHIlPL7g55U1RxO8L0TnyFzJOx0G74X2Cu4VckclnymSgYg2+0Vwer24BGKnZI4lpUX/q4u2dpvB2Vw7kTHsG1WuGd+4woOPMetTV2jxDxgyLOwUHC+HUXbMqNDxtVvqzRCWwdKSxAcO3DG/Xdqy8+P5JZY3UgGCOMO3cx4JcqYAKM/xC87cFk5mwuB6MEhsQGLw9hrtbaRvnkSwZRKhX1HRtn7lXcS/xHkGkmHcCQx2FwqR9XwQe0jWm7ZGkhBKg/2L85g8p/aYCbvOtNCE86DC4VOTviqCqnIc4vMGIvEp2DA6LpddgtJ5S+yaFDtrBNHkFl87ru7sfTxR3pFGqEOzKcbRdSsIPawiPY6sS5LpebWoJNhkch0XVD6YQ2QKBTeLA8If5AtCbDjE0+qbF8YZD9oT69EUvwYsGLXDPAGBY+r/Y75QMMfaMH5w+qiDnJDSNvO9UVPXBsZK025pBPycK3xTOQrtvXjHqYRDoPNO7NFz2UfUApIYm38uzfD8hxNRRmJg5KhPvAW7i4o8nNWGY8OPeU7kOYBHAcZyVDxzapWghW1v1k0CF2ibKOq+ruS6UlKHuX/EQ9KqkQTuc+l4A/FyAkoDUHJSkBKzUZbctT+28DR276YCBwMmm8igL//6HUbzM70dEXGrW/yOMgfDZNqzwIwhKvt7bQKWMxPpmeFlUrgUfzYgQHQK4Kim94Msyh3xYbLMQviIyd9fvxz0xCkkAKR8hn/Y5EWVKtM5pYibeXmIGOIdmjnejo8m3CYUSjx/pjvI1PFTG/6LUsdFBizf7fjNbYj+isplOU3bZXk01ycYOaySqXoXgIAYZxgATY6O1xknyY+4bUdsnbr3gwySCt5qVkpYQqGes43gFmGAMzTHO1tjsJ1hWke7aqQ7b7uqtZ9cIeGCfsD/eBv8z5TBNk3FqD3bzR9llQjwc8u5Ki6vSanlaTHbYe0A0DweuDYcAI0dg5fpL61i7jzE+0jwz03rOqxRKMdJTCIL9J1C7LufdPhRwsof7"
    }
  }
}
