apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich.namespace.yaml
  - immich.library.pv-pvc.yaml
  - immich.redis.secret.yaml
  - immich.redis.yaml
  - immich.database.superuser.secret.yaml
  - immich.database.user.secret.yaml
  - immich.database.yaml
  - immich.config.secret.yaml
  - immich.helm-release.yaml
