apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: platform-monitoring-grafana-database
  namespace: monitoring-system
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: grafana-database-cluster
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: cnpg-system
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
            - port: "9187"
              protocol: TCP
