---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-database-user-secret
  namespace: monitoring-system
spec:
  encryptedData:
    password: AgAfRxloKeCJ3knlgY7Jg23JQunTmSJwijlS/nMj80ULIqTBEHR0cLFqtS2MhvZWeih0XwUcv/pQVtwDq56Ra7uH7Q0G3tW4DMznwNyrcn7O8yyRcQfzuIFiWCOPEH0c8OsDzEiqUlAQVjAXFOXiY2c8SfiQPdiVz0bEeYBASJiywc4GGy0Vdr4LALTNlGCMpKySZthHs2/v+pWe0iKjd9Q5r5F2BRNachS+EWbVqmh31zIpLW6pbLTK30EyeyMlpQvYLOXGJ9qI3p9GeyajH7eU2hi3+bjtYrKI7Po9KzO7o1fanhRev6iTyXqRXQY4rEX2AQtTpwqDtEnq0CUSoi+2m1zSn5WVDP2+4bJ1+7VbPUqNoqogNgUgzyr8o9BDcM7jMT/IQbDOThsGsKuhcJsFjpKDTdO/rB1/F+/iyKD6od7TsCedc2vrZmnLKV7xTsggJI/VbLdP33yE4dndSY5yt9Z80Tg9jL+M46R16RGVGIwp8K0MkiszAo/hjEy09zUOy6BxrexySsxlsDCcBLCUl7q5as9NlGCyj3H/QgqKzlnHyryYpA9z/IdAg3y4hJx6UiIaFflUybK6rzUtZqavbCmINUBPYat/KWaDU8zrIp+1Ku57gP4CcTvZShgc2qIB8a0PPF206hYGUnrWjAeqa4rryI46qQi97J8tZrTIibznlMTiv4XRngwDw3J6VStIhXyafn8iU2E9j69Ou/t+DRqRl4D3TlqHw38Pz6fldvMFWX+MXPRadJoepTPequlw142qn3ENOFtF68xPOxI8
    username: AgCVDw5h0A4fdTeE3plw54g9f5lvZcQ0dQ24kEeq8+uNwqtB0CuMYVrindQnwUxBra5FdHq9QqgNs2sW61IjQkt1YPh7XUYZdYfSBREsa7luwGSx/ZE22rP4nVOriWKQNNV3U15dSZU8k2JU67i25p6yfOh7MVWzdDclLfIGmxLAAzOspUJNAlMU06JhBevJlqTeQUDqx7NGGfsEsSVllJ5xOo4uopSHBjVzb7RCywI9lfqh6Sczqbt0mvH4aAS92MJxtxp+8z8/a0A4Gpv7YJhwp9UeceK1bJmJ+BqmtfO4OPNOEroWSQkYJzk5+GKpvm0PzBEYUb2JQdlvZ2UoE/JnnLy/VmsigmyS0V2t/RvA1oyBWZSnwc0ThA9R82Xkw9YWp6MxWQyJq2py18rU/cQdlViewHnY9SQJbXkg7lOx52js6dHkXeqeAbtm2tOiPCYB2+tNkyDLvmCGOS4QJCaHBEzWPj7B6ibZ7EP7hESg0OgUw+PuwMY8XLIxfRBaL58twi0ImUtXfFMPr+ApE95DnS9hh2w3N7K4TH099HCGqtpEqOAlRMM/3y/9BDiKJsYZ3wKXRluBNy7vyTf4WKBqw0x1aeDBoPAskmVgeVYlEjQM8mu6TCLhAYHx8VdYwqwjKDD1jYOPXO5aXJvzkh+uvb1P5sQPk9Q1n121PsJUM2+hX+yJHc8PW6kbOQHNdWWiYZdz4na1
  template:
    metadata:
      name: grafana-database-user-secret
      namespace: monitoring-system
    type: Opaque
