---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telemetry-credentials
  namespace: monitoring-system
spec:
  encryptedData:
    TELEMETRY_PASSWORD: AgBzuYuDtPU6QAHlZqmtcI8o9ljusbw3FEQl213Mf8HuCBkTWERuU9MlObhpswk8XxS6DSzO2Da6TUGcTtuSHRfWDM3rq0p18VF7BhxrJSxMELhB/eKHhNRJVFHl35OQfDU20koMyVAG1kf+2qhqdT8keXyyPuOqqRzb7rofRpUYrMd+aws+p7RgaUvcctbFnjpleRuEzPkkuk8vyzaCp7l9EBpM1Xcd0tUZf2PTIkyTx9C7OkrBrgJ1fmXsYpUu3e6vLv6SFB5RTpDYJZdX2VqAfwQDAZDTRzY2pEYTYzGDSAFvThQ+TRFNY7p+KR0UwnFe5lr5JPW9HOCYUWOWLDVB31RsQSYw0pE5i2k9WTkkcMefqhSU9qSlJb2btM82QeNPDwj3Zmp+zzPcSesqGrkOkrb69PXeFbL8wZo0Ov7PdGFeZlUrGYhKbO0Mw+7mGYC/P85rt5CSYgcBWz8iBHMT1PEZy5TADqqRNpMyAi1Fvj91q8InOKo+T4Z7CqH7HiFA6sdS3K/puYOWSGEBQqEQ+BHS5Wo/5ogjUamlvTOzoKEBfCV7sXbF4K0GCYyVspY55bqp3MtvVBjgWvjDkqmojVWeWgG/IE584Tc1hdaXNFtg7R365yre4Zj/anAeCRVh19cq1LBr9/XlTTuyhXMvdbxRePeDNlfZmYeX53kMmegE/RPLNpxksDrrhYJR1dORQONUNFh7tPoKhdLjrtY92MbsQWecoh6qWwl0bJilzsHHj8ibGoujTDANXSwHosA=
    TELEMETRY_USERNAME: AgCQTgncmEy4QoK3/PCupYWrNM4Yl2cAd8F1hDto08DqrqCV1l29V1yRjK8fO/p4kYjw72GIe/o6qojQq/etGrtuv9kvlkgnSbApClsMLbr/zGo7qH7Np4MGYahEbidkM1wakh4pn8LQBNWYhYPVwnSrugXMUggFUSL+SJJ+5vBKZaFjemmZZudI2X55mFQhG4dM9U6z5wfjj/HirxYrSMG8wW2jXp6mu6HRxwY/yV8V3hH/mP+Ep2FcCQIaDO/tU/YgLtGbup1Cngm2Idc9Xb9PDfEKLZasgJwpOJHVwXWxJEKp2SWbmOl75DpNSApqg+M/Az/8qy4z69aZqkPXukxEtgP2uPL2ijxl6j5WBkmZu8MTmp+38ZZO7Wkq0MsM2qsdaYIRDnJTGAhLKHeqijIogNWNUK/HgrvS/y95T7aVa2jJq3+qMen27RN0udkBGS2ynpck93ACPmBOMR1hd8QWxOGzFyPbta1lFq5rzDplPtUzBjv5nSuwI7/UV4St7pDIAFkp4FP6PqdZrOfSiuN8FRFdzbROrO513K7sSglUi80H1ouYCqOlxc3MGgyX0J6PbOE919ftsKl/OxRbceE7KWsJXMx2Xxr7LwxDK4Wi0JjWeZf2d1m4lnTJTZe6P2kyBAOHwIIluiiWfwCk/7+HmHaH4BRE7zeIrM1yMAepDP5264x4+9RZjsTSRqFbus588q6PhDuq
  template:
    metadata:
      name: telemetry-credentials
      namespace: monitoring-system
