apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: platform-monitoring-grafana-database
  namespace: monitoring-system
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: grafana-database-cluster
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: cnpg-system
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
            - port: "9187"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik-system
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: route-grafana-database-backup
  namespace: traefik-system
  labels:
    networking.tinyrack.net/owner: monitoring
  annotations:
    networking.tinyrack.net/hosts: storage.intranet.winetree94.com
spec:
  description: Allow the Grafana database to reach object storage through internal Traefik
  endpointSelector:
    matchLabels:
      io.cilium.k8s.namespace.labels.networking.tinyrack.net/isolation: enabled
      app.kubernetes.io/name: traefik
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring-system
            cnpg.io/cluster: grafana-database-cluster
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
