---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring-system
spec:
  encryptedData:
    admin-password: AgBb6kexyQIwQ2kIRcsZiNikM5aNiKbsD24blcrEjV9fpe6pbmeEOjPLgnmF0P9kJ0VF5Zc33v9ePk5hnCmMSSJzf9/Dulfgided4F3f5U1BLsV/7BaGnuy3F+w3wYD40f5YvwhZzv8KhwFs04zuUcfH4FaX/9Ykl5wfEbGDZ8Y53qNWODDSiY4vjujEnT90hnYpCEGIXx8E2Z+qt8BVee7SX2zwGMiw1K0bXF4zHV4PWIx4j7pRehVcEU07YQqjntXVBa8xhSH/lxhizMGJo4GtEzKby1I3x61JCWOIBQi5+BAE2DRYGg48AvNYY1wBBItsMZgHmpIqL2+YkafFYM+vAHiTuWyhu6HSjhesnH6N1tACSpJMhz0QHH0e5UDoSOkLA28H2YYMfu83FxI+uSpNitqjz3Y+fE7T0bT1cmaQWZIrYAy0FJ6z6kaZ4XKNyK0fX1WCqbNJ4HJYrm/yavNp9ljVdv935BNSy3D1ZXRuBSMMNdOgkKZhyFBxcjcaYWpmGeDiXpTNUKXqUoyDDPFKSYsJNIln0ItDstzDjNrMnGExj4lVv+F1VkdIWrf/ixWYr1hSRA/VpOf/zlt6diG8PlBzM7liI7KOBOZtsLeKgO6o3Lz8wVujpY+InLTmaaBbeYx18PIYGQjL1q2cYjRM4sZM6W4qAaquJYZkHZPx8TO/c8pOHmTjgke7OpI4WERLMLv6R+2LSpsvtQxXdzAOWoduBXabtrCK24AhCsuS7kxRC534xkSILT72KuUKAgE=
    admin-user: AgAsZGwMLyyHHHQUFOIN1btLg5zdn6vWf90ZzRt7rldr60fv0Vy3ZX6j84gyF3QX9+MOVfZ62MXYMN2xIoMClDJd2RuNAPCx11qYJl0XSRGdUnm9FsAN7r+BD0YuqWvxwGwDx36BtoTORNMmTV2WhDJW4I8c8DPcHD3IMRgMxdyaYOnNg/TAP8Zpt0i3n468DwxPhxxcvfLI5YeqM+fL2T5c5GCegJ4JiGXVFu3dvXMrP8r98BGWESxNuXSEqshGXhNifqXVd3CeDcSqVwMmfBxmhhpZjJrKtv3uu2u+qjX4PTuzextzx9iPBSBbPfeLfe4vg8nu8ZLvkyPH5AehNw6uQwnIl0jY96wp1equfs7Rx7nk2Rgs7nhOO1gJmEjMG3MyaboWHG1XhwygP5OpK2LYa7TztoQt7ZzLRRMcZbSVhbw0a9g3M0ru70AqvJ111aJc/5Bewo9akkywbO0m4Y3vg2jU1uWubKWvHWNQoZ05S/V/HP7zq/rEdYGyehZd4dtzM4M2BkKWztCkxK6OSx0XYYAO74sTlNGQk9WXSy3HE7AlA3806u7IZ1YFs3D59CAeKzsP7K16xK9JHyITdLR09QBCBQDCZnIKJiCaA5nUXWW/tq9CubhcC/y/8oVFXRkaNX8V4NnPJGj60uiA0xKkVn4ctttvDRgUDMwulUcLR9h04R/cLLovxUqkBKcNVHIXXsYYIA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring-system
