---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telemetry-basic-auth
  namespace: monitoring-system
spec:
  encryptedData:
    users: AgBv07JlCocfefkqd9vcjlsiD0iP4g1IQMT5O/6iDvav9vLJw3nbZmxOkxpexwaE+cW/CbFekLlUotUetOLMv3tM2LADTiWls/rpUhQYAwxt16rKu/2aRYi6BiyYiPC3GgZ33xYCvJTo9RFtOjcnHGsFMXYaTPDi7zSo24FbgSXERnv8ETd8aUWcZ1XHPha9ywTFvtdNJlS8pgYntRL2ycj72VgQfExQ9Ntw+xDx8KpHqFwVX3vukq3Hs3/W+6BByPjV6Kgwl5Ar0eRyH1SzRKO2t8IO9drOtAwo4fCB56SKgqGrZU/jIS/GEFSdUBM6hVJlTcuAjdKWQRKe2HAiXkfBehptANoxf7No+5jW27Ywh431e1EHEW4BUXLovRBPx29sQhmk+rz1CCcTrHIGwtxagEqavW0oA6Qe+uxeD3/RF8srRLF+ib9CT2na7JnAi1JAk0jjBszuvicgR8vSx/MVRPZWID33sLuQ2DbwTc/gYj9eg9lkvxoNsFJqrxELehLs+8xoj9ogAqd4BcmVnL/tJaFFYIkixVO+Sa6+pv3ymrsLjEle2TdixL+4yaJKvWm+Duz/9a9L7v7BgdgPgzUM2DU41yL57yg87tcQ42uMSIbuKxf2K0OVE1la8D5lr5tMeKYtDpbDEOXX6cgDPHRHvyV+gQaxNsQqdrVImVpqJX6ExLfnx9ncgd27UaEkw7Dzngz+r1hOKsu9lOcApkp6e/gUlTANPd3LPUgce8szivdrzmWEmfJN0tFWRCKdI8NpIBhFSzozJ2yhJIs0BAwTIi6UuQn1UhTF7iaxmiQm0ZYjAZfIQGyhY0v5MGovzQEDxFE0aIyxqVWRyrLqYE8VHGZYCn6zF7GZrsQPWO7j0yg5QAAdymsnxfzch/u5PQ==
  template:
    metadata:
      name: telemetry-basic-auth
      namespace: monitoring-system
