---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: issuary-grafana-oauth
  namespace: issuary-system
spec:
  encryptedData:
    ISSUARY_GRAFANA_CLIENT_SECRET: AgAgQExRHdBolRiWBMMT34fes8IuUjpoH+Rg3pHok96c0ek+9ecmzEWluEHGydk7Og5PF6K9bKcXNbhz40gOutuDoccTVPB9aGqRMlh+UOPMr4i4kviaoiRlHC/s+OU/iaMFjod5RTRT183pyiEB3bLXKJuQ6EYSY/Tmg6aExivvMGrRPI53+XkzrShSitXbgGc4PXZLyNUNABjMfrmBNKmF1P6HrPmlBt7tmEVQO8YeGRvkMx3Ed5317ukX3auKPNSiH1bkAQKX0Hexs3lbokmZND2cD6i8Ms/aa9vQVnJyM1jLzWSubMDiGTyY2Mg1jUTU4FtF10J0K2U+WMG7KZ+DDoMqGWTW0P21c7dYpDwvGGNmRZTXr8iAG5KC7cn9v8aOEOhBDXFr1NWnCr0kZB90uvmTnAXM5OM6uzW29EA4f41iPiDrJGH/rkxRGfDinz9A3zGqO6qeeqndpWyYJhdkDhPpLUBj1UY04LaZf26Y8LEaL+nfGQKNEBBrVeg3+QLB2zglzUeb5thfkAP8yg8oaCeRVs9KrLOYFfhQXtTBWLRyxt6e+JRJLN+namx89oInPnkngVA/4i9DuGZ+KuNhbdHO7IC5ZYRZtFSuGNatUALR1AV4JYISlWTjQHH6EwdV2j0MauHVNFfa87jlusiVUPnJCUbRM9R9ZRrhp0RHwPDfQnzU67aMYf8UvLo018ZZxPeJoLf4qOkddRA44noXSHnTsOUHJ/BFN4/1d8ByaQXIoSq4NW2EGIR+OAa5xu2p2GKnaXJkO6rhvchk6PWd
  template:
    metadata:
      name: issuary-grafana-oauth
      namespace: issuary-system
