apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: app-rustdesk
  namespace: rustdesk-system
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.namespace.labels.networking.tinyrack.net/isolation: enabled
      k8s:io.kubernetes.pod.namespace: rustdesk-system
      app.kubernetes.io/name: rustdesk
  ingress:
    - fromCIDRSet:
        - cidrGroupRef: lan
        - cidrGroupRef: vpn-server
        - cidrGroupRef: vpn-control
        - cidrGroupRef: tailscale
      toPorts:
        - ports:
            - port: "21115"
              protocol: TCP # NAT type test
            - port: "21116"
              protocol: TCP # ID registry
            - port: "21116"
              protocol: UDP # ID registry heartbeat
            - port: "21117"
              protocol: TCP # relay
            - port: "21118"
              protocol: TCP # web client
            - port: "21119"
              protocol: TCP # web client (TLS)
